### ISSUE TITLE
unable to print the images inside html

### ISSUE THREAD

**Issue by venki0552** [katzer/cordova-plugin-printer#100]
any option to print html with images in ios. 

Thanks in advance.

**Comment by EionRobb** [comment]
works fine here.  what console errors are you getting?

**Comment by venki0552** [comment]
I am not getting any console errors

I am using HTML5, anguarJs

images are specified in images folder and gave the path b using image tag.

**Comment by EionRobb** [comment]
Are you providing relative paths to the images, or are you accidentally prefixing the src with / ?  Are the images part of the app or are you trying to access them via http/https uri's?

**Comment by venki0552** [comment]
Yes i am providing relative paths and the images are part of my application.

**Comment by trostik** [comment]
Works here too
demo `<img src="../www/images/logo.jpg"/>`

**Comment by MAOstrander** [comment]
I'm having issues as well. I'm attempting to print some generated html that contains an image, but I can't get the image to render/resolve on the pdf. I've tried the following:

`printThis.doc = '<div class="test-div">`
`        <img src="./img/test.png" alt="./img 1">`
`        <img src="/img/test.png" alt="/img 2">`
`        <img src="img/test.png" alt="img 3">`
`        <img src="test.png" alt="in same directory 4">`
`        <img src="www/img/test.png" alt="www 5 ">`
`        <img src="../www/img/test.png" alt="../www 6 ">`
`        <img src="http://lorempixel.com/400/200" alt="lorempixel 7">`
`      </div>';`
Only the LoremPixel image works. I don't want to have to host this single image for printing purposes, that seems silly.
I'm having similar issues with stylesheets, only able to use inline styling.

Appreciate any help with this.

**Comment by brienpafford** [comment]
http://stackoverflow.com/questions/9073953/phonegap-on-ios-with-absolute-path-urls-for-assets

See top answer. Use the cordova.file.applicationDirectory + [WWW_PATH_TO_YOUR_IMAGE]

**Comment by katzer** [comment]
A relative path from the `www` folder works.
I tried `<img src="img/test.png" alt="img 3">` and the image was there.
