### ISSUE TITLE
unable to translate

### ISSUE THREAD

**Issue by fbalarin** [katzer/cordova-plugin-printer#101]
How to show the interface in the user´s language?
I did not find any way to do this.

**Comment by katzer** [comment]
What interface and what platform?

**Comment by katzer** [comment]
Please re-open if needed.

**Comment by R1Daneel** [comment]
Platform: iOS
Device: iPad mini 3

**Comment by alizeegtd** [comment]
Is it possible ?

**Comment by katzer** [comment]
The labels and the whole UI is defined by the system. The plugin does not define any labels.
