### ISSUE TITLE
Preview not showing until disabling double side

### ISSUE THREAD

**Issue by jacobo3d** [katzer/cordova-plugin-printer#102]
This is on iOS 10, and I'm trying to print out an image (https absolute URL in an img tag). 
Preview is not showing when the printing dialog opens up, just a blank page. If I disable double side, which is enabled by default and I haven't been able to change it programmatically, then the preview refreshes and it shows the image, but not always. If I cancel the printing, and open it up again, then the double side disabling workaround won't work.

Thanks!

**Comment by jacobo3d** [comment]
This is what it logs out when I tap on the Double-sided toggle:

The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x100fbf0b0>, and it is attached to <UICollectionView: 0x10130e400; frame = (0 0; 375 250); clipsToBounds = YES; opaque = NO; autoresize = W+H; gestureRecognizers = <NSArray: 0x170658420>; layer = <CALayer: 0x170420d40>; contentOffset: {0, 0}; contentSize: {0, 0}> collection view layout: <UICollectionViewFlowLayout: 0x100fbf0b0>.
2016-10-08 09:23:30.092845 MyApp[867:266198] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
2016-10-08 09:23:30.985816 MyApp[867:266198] The behavior of the UICollectionViewFlowLayout is not defined because:
2016-10-08 09:23:30.985886 MyApp[867:266198] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.

**Comment by katzer** [comment]
@jacobo3d how about trying `self.automaticallyAdjustsScrollViewInsets = NO;` in your view controller? I know some cases it helps.

**Comment by katzer** [comment]
> If I disable double side, which is enabled by default and I haven't been able to change it programmatically

To disable the duplex mode at all, just set `duplex: 'none'` when invoking the _print_ method.

**Comment by katzer** [comment]
Please re-open if needed.
