### ISSUE TITLE
Printing from IPAD in A4 prints in 1/4 sheet

### ISSUE THREAD

**Issue by ma4xat** [katzer/cordova-plugin-printer#103]
Hi, im trying to print with ur library, but i have a weird bug.

In the preview, "my design" occupies full sheet, but when i print, it is printed in 1/4 sheet

![image](https://cloud.githubusercontent.com/assets/3372517/19703190/349a285a-9b03-11e6-9757-937578df2938.png)

![image](https://cloud.githubusercontent.com/assets/3372517/19703223/5007a612-9b03-11e6-92dd-f07f63a50590.png)

Any tip?

**Comment by ma4xat** [comment]
I just check that it happends with border:false in options

**Comment by katzer** [comment]
Usually `border:false` is the better choice for images but good that you found a way.
