### ISSUE TITLE
Cannot change settings.  Try Again

### ISSUE THREAD

**Issue by TimKohler** [katzer/cordova-plugin-printer#105]
Hey, this seems to have just started, might be a google thing.  Using 0.72, when i call .print(), the print preview comes up.  

If user changes teh selected printer (even if changing just to 'save to pdf') and then hits the print button, an error is displayed saying 'Failed to change the settings.  Try again.'  There is a retry button, but clicking it doesn't do anything.

Have you seen this before or lately?  Again, have been using the plugin successfully for months and this seems to be a new issue.

**Comment by pittfarm** [comment]
Did you c resolve this issue?  I'm getting good the same error.

**Comment by TimKohler** [comment]
I could not solve.  I ended up using android studio to create my own version of this plug in.  It is def an issue in the PrintManager handling in the plug in.

**Comment by katzer** [comment]
@TimKohler Haven't yet seen. You can share your code here if you found a fix.

**Comment by cdavide75** [comment]
Hi,
I have some problem.. please can you share you solution and code?
Thanks
