### ISSUE TITLE
Crash on Windows 10 Phone when trying to Print

### ISSUE THREAD

**Issue by jainpiyushb** [katzer/cordova-plugin-printer#106]
I am using,
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Node Version: v4.4.5
Installed platforms:
  android 5.2.2
  windows 4.4.3

I am testing this on a Lumuia 650 running on OS Build 10.0.14393.321 Version 1607.

The app crashes when it is trying to generate an object which conforms to IPrintDocumentSource at MSApp.getHtmlPrintDocumentSourceAsync in PrinterProxy.js.

If you remove the getHtmlPrintDocumentSourceAsync() method it presents the Printing UI with options to select Printer, pages etc and obviously with no content. 

Any idea on what can be the problem ?

**Comment by katzer** [comment]
@jainpiyushb I can confirm that its broken with OS Build 10.0.14. Seems to be a bug on Microsoft site.

**Comment by katzer** [comment]
I've added a hint on the README. So far I don't have a fix for it.
