### ISSUE TITLE
Print PDF file

### ISSUE THREAD

**Issue by pseisog** [katzer/cordova-plugin-printer#107]
How can I print a PDF file using your plugin ?
The file will be donwloaded from url (eg like http://www.somesite.com/files/myfile.pdf) and I want it to be printed to a choice of user to a printer.
I did try something but it returned 'I can not open options' and the RETRY button was frozen.....
Android 5.1.1

**Comment by shineirvin** [comment]
did you found the way to print pdf/image file ?

**Comment by pseisog** [comment]
Hello,

Unfortunately, I did nothing and nearly abandon the project......
I couldn't find even one simple example of how to call the plugin using an
existing pdf file.......
I would love to have the simplest example of how to call the printPDF using
an existing file.....
Thank you in advance !

Pantelis

2016-12-14 5:59 GMT+02:00 shineirvin <notifications@github.com>:

**Comment by katzer** [comment]
The plugin does print HTML encoded content. What you're looking for is sharing a (pdf) file to send to your printer or any other connected service.

**Comment by pseisog** [comment]
Hello, 
Thank you for your reply !
No, I do not want to print HTML file. You have a sample code of how to create and print a PDF file. I just have the PDF file already and I do not know the syntax of your API of how to send that PDF file to printer. That's exactly the sample code I am asking from you : print an already existing PDF file....

Στάλθηκε από το iPhone μου

18 Δεκ 2016, 12:22, ο/η Sebastián Katzer <notifications@github.com> έγραψε:

**Comment by katzer** [comment]
@pseisog I know what you mean but the plugin isn't doing what you're looking for. The plugin allows to print inline HTML snippets.

There's a sample code how to print PDF file: Listing 5-1
https://developer.apple.com/library/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/Printing/Printing.html

**Comment by katzer** [comment]
Please re-open if needed.

**Comment by rmabunga** [comment]
hi @katzer . So I am using this plugin to allow our users to print a pdf file from a url eg: https://example.com/sample.pdf.

It works fine on iOS, but only displays blank page on Android. Can you help me with this issue?
