### ISSUE TITLE
Print silently

### ISSUE THREAD

**Issue by alisterwood** [katzer/cordova-plugin-printer#108]
Hi Katzer,

First let me start by thanking you for such an awesome plugin.

The small issue I have is the dialog that comes up when you specify a printerId. I get the "connecting to xxx printer" every time I send a print job.

Is there anyway to remove this popup? The prints come out great, but it's a distraction from the app with this popup

Many thanks

**Comment by katzer** [comment]
Thats a limitation by the SDK.

**Comment by gabrielstuff** [comment]
It appears that it might be possible to do so. Reading through : https://stackoverflow.com/questions/13145724/ios-print-without-allowing-uiprintinteractioncontroller-to-appear and specifically https://stackoverflow.com/a/40610378

2016 - iOS 10 was already allowing such a thing. Could you elaborate on the limitation your are speaking about ?

**Comment by gabrielstuff** [comment]
Ok reading through https://github.com/katzer/cordova-plugin-printer/issues/42 it appears that we can do that with a `url` param. 
Going to test this. Thanks !

**Comment by savageqm** [comment]
> Ok reading through #42 it appears that we can do that with a `url` param. Going to test this. Thanks !

What about preventing that progress dialog that appears when you use the URL?  I was hoping I can print without any user seeing anything related to printing.
