### ISSUE TITLE
Is this plugin supports the USB printer?

### ISSUE THREAD

**Issue by shanmuga-axatech** [katzer/cordova-plugin-printer#110]
I have a doubt on this,

is the plugin support to print on USB printer via OTG cable from android device?

**Comment by EionRobb** [comment]
That works if the printer app supports it.  PrintHand/PrinterShare definitely support that (as well as Bluetooth and Wifi printing) although most other print apps on android are wifi only

**Comment by shanmuga-axatech** [comment]
Thanks for the quick reply i'll try and let you know.. I am preparing the setup from android device to OTG and OTG to USB printer

**Comment by katzer** [comment]
If the system finds the printer then the plugin also. USB printer should work. Bluetooth printer need to support AirPrint to connect with MacOS or iOS.

**Comment by Yethroy** [comment]
Is this plugin supports the Built-in printer?
As for me I have the android POS that have built-in printer and I dont know how to make it print.

**Comment by shanmuga-axatech** [comment]
I have printed the document using android implicit intent and epson sdk https://c4b.epson-biz.com/modules/pos/index.php?page=soft&scat=61 and the ionic plugin http://ionicframework.com/docs/native/social-sharing/ with shareVia api it's works fine for me
