### ISSUE TITLE
Position of pick dialog (iPad)

### ISSUE THREAD

**Issue by Fauphi** [katzer/cordova-plugin-printer#111]
Hi,

great work on this plugin, works great!

But I am curious if it is possible to change the position of the pick-printer dialog window on iOS/iPad? Appears always in the top left corner and it would be great if it can be moved to i.e. a custom print-button.

Thanks.

**Comment by EionRobb** [comment]
Specify the `bounds` in the options (second parameter to the `.print()` function)

**Comment by Fauphi** [comment]
Ah, now I get it! 
You can also set it on the `.pick()` function as a second parameter. And it has to be an object `{bounds: {left: 300, top: 200, width: 0, height: 0}}` not an Array (like it says in the docs).

Thanks @EionRobb !

**Comment by katzer** [comment]
Hi, `bounds` can be an array also. At the end it will be always an array...

```javascript
bounds: { left: 300, top: 200, width: 0, height: 0 }
```
or
```javascript
bounds: [left, top, width, height]
```
