### ISSUE TITLE
Is there an option to save as pdf instead of printing?

### ISSUE THREAD

**Issue by immnk** [katzer/cordova-plugin-printer#112]
There are options to print and the user can manually select the save as pdf option. However I'm wondering if there is an option to save as pdf to come by default so that it makes things easier

**Comment by katzer** [comment]
Unfortunately its not possible. The SDK does not allow to communicate with printer in direct way.

**Comment by EionRobb** [comment]
It is possible to save direct to a pdf file, with changes in the plugin.  I do this in https://github.com/EionRobb/phonegap-print-plugins/blob/master/Android/PrintPDFPlugin.java and https://github.com/EionRobb/phonegap-print-plugins/blob/master/iOS/PrintPDFPlugin.m
