### ISSUE TITLE
Bluetooth Pinter Endless Searching

### ISSUE THREAD

**Issue by klospammer** [katzer/cordova-plugin-printer#113]
I use bluetooth printer to print but when I search using this code `function pickPrinter(){
    cordova.plugins.printer.pick(function (uri) {
        alert(uri ? uri : 'Canceled');
    });
}` it lead me to endless searching printer, any advice ?
my printer is 58MM Portable MINI thermal printer.

thanks.

**Comment by katzer** [comment]
Please re-open if needed.
