### ISSUE TITLE
Plugin doesn't find my printer

### ISSUE THREAD

**Issue by lucav90** [katzer/cordova-plugin-printer#115]
Hi,

i want to use your plugin to print same text and image with my bluetooth printer but i have the message 'search for printer' but that more time your plugin doesn't find my bluetooth printer.
My printer works with other plugin.

How can i solve?

**Comment by katzer** [comment]
See #116

If the printer is not listed on the preview screen, then the system does not know them.

**Comment by katzer** [comment]
Maybe the printer does not support AirPrint.

**Comment by katzer** [comment]
Please re-open if needed.
