### ISSUE TITLE
App closed unfortunately in Android 4

### ISSUE THREAD

**Issue by lucav90** [katzer/cordova-plugin-printer#116]
Hi,

i have tried to use your plugin on android 4 device but it broke the app with message 'App closed unfortunately'. This is a bug.

And in other device android, your plugin doesn't find my bluetooh printer.

**Comment by katzer** [comment]
@lucav90 Please send me the stack trace if you have one.

Re the bluetooh printer - if the plugin does not list the printer, then the system cannot find them.

**Comment by katzer** [comment]
Please re-open if needed.

**Comment by pbaezab** [comment]
Thanks katzer, but for me, not work.

Android 5.1.1
'App closed unfortunately'
