### ISSUE TITLE
Extra blank page is landscape mode

### ISSUE THREAD

**Issue by sagrawal14** [katzer/cordova-plugin-printer#118]
In our app when printing a page with `landscape` mode, we are getting a 2nd blank page in the print preview. First we, though, this is just in the print preview but when we printed with the printer, we are actually getting the 2nd empty page.

I tried to fix with all sorts of print related answers available online like setting up `min-height` or `height` of the parent elements but nothing worked. After the research & investigation (saw issues #69, #24 & #89) of 2 days, I'm creating this issue.

So when I'm running the command: `window.plugin.printer.print(html, {landscape: true, grayscale: true, hideNumberOfCopies: true});` here is how it is showing me the preview (which is showing the 2nd page):

![img_0810](https://cloud.githubusercontent.com/assets/1804514/21342773/b3d9a9b0-c6b9-11e6-8a69-05d7f500c5fa.PNG)

When I'm passing the `border` parameter: `window.plugin.printer.print(html, {landscape: true, grayscale: true, hideNumberOfCopies: true, border: false});` the whole page got divided in the 2 pages instead of 2nd page being blank:

![img_0811](https://cloud.githubusercontent.com/assets/1804514/21342824/e82118f2-c6b9-11e6-9254-224c7c56d0ab.PNG)
![img_0812](https://cloud.githubusercontent.com/assets/1804514/21342826/eb044d6e-c6b9-11e6-8acb-f6124f5e4d4c.PNG)

I didn't try yet with the actual printer with the `border: false` option. My development environment:

**Mac OS:** Sierra 10.12.2
**Cordova:** 6.4.0
**Cordova iOS:** 4.3.1
**Cordova printer plugin:** 0.7.2
**Device:** iPad mini (Model A1455) iOS 9.3.5
**Simulator:** iPad Air iOS 10.1 

After all this investigation, I created a fresh Cordova app (with the same above environment) and tried printing a simple text in the landscape mode and it is showing the similar behavior (i.e. 2nd blank page):

    window.plugin.printer.print('<h1>hello</h1>', {landscape: !0, grayscale: !0, hideNumberOfCopies: !0});

![simulator screen shot 20-dec-2016 1 44 24 pm](https://cloud.githubusercontent.com/assets/1804514/21342970/986182e2-c6ba-11e6-8da5-476eaaf216d1.png)

**Comment by katzer** [comment]
hello @sagrawal14 I've also heard from others. It also took time for me to adjust the HTML snippet in the demo app so it looks same and fits on a single page across all platforms.

You can try to scale the page, to shrink the content just a little to fit.

**Comment by ransikafs** [comment]
Thanks @katzer I'll give it another attempt for fixing it. Do you have the sample code of HTML snippet you tried just to have a look how did you make it?

**Comment by sagrawal14** [comment]
Thanks @katzer I'll give it another attempt for fixing it. Do you have the sample code of HTML snippet you tried just to have a look how did you make it?

**Comment by katzer** [comment]
That's the sample app
https://github.com/katzer/cordova-plugin-printer/tree/example

That's the beautiful CSS snippet that took some time to have it looking equal across the platforms.
https://github.com/katzer/cordova-plugin-printer/blob/example/www/js/index.js#L72

You could start with transforming your body. Maybe it helps.

```css
body { transform: scale(0.9); }
```

**Comment by sagrawal14** [comment]
Amazing! Thanks @katzer

**Comment by sagrawal14** [comment]
Just to update, I got this working by setting `height: calc(100% - 10px)`
