### ISSUE TITLE
Just to notify you of a few important bugs at your excellent Cordova Plugin Background-mode.

### ISSUE THREAD

**Issue by v3ss0n** [katzer/cordova-plugin-printer#119]
https://github.com/katzer/cordova-plugin-background-mode/issues/216

https://github.com/katzer/cordova-plugin-background-mode/issues/212

https://github.com/katzer/cordova-plugin-background-mode/issues/211

**Comment by okan** [comment]
Mehhh. I guess it doesn't matter for him. I've stopped waiting for a response.

**Comment by katzer** [comment]
@okan You should never give up ;)

**Comment by okan** [comment]
@katzer absolutely. :)

**Comment by okan** [comment]
@katzer absolutely, I've stopped waiting for a response. I'm still looking for a solution :)
