### ISSUE TITLE
Extra page (label) printed no matter the settings

### ISSUE THREAD

**Issue by eugenedw** [katzer/cordova-plugin-printer#120]
First off, great work on the plugin. Much appreciated.

I've read through issues #118, #69, #24 and still can't keep our label printer from producing a blank label after the first is printed. I've used CSS to limit the scale, width, height, switched between landscape and portrait mode (landscape prints 4 pages, while portrait 2), reducing the label content thinking there might be blank lines, set duplex to "none", removed the setting altogether,  I'm not sure what to do next.

Here's the code for my label:
`<div id="labelinfowrapper" style="padding:0 !important; margin:0 !important; height:19.7cm !important; overflow:hidden !important;font-family: arial; height: 150px; width: 100%">
<span id="child-name" style="font-size: 30px">Susan Doe</span>
<br><span id="checkin-location">Test Location (ATSTION24)</span>
<br><br>
<b>Guardian:</b>
<br><span id="guardian-info">No Guardian Found</span>
<br>&nbsp;<br>
<b>Allergies:</b> 
<span id="child-allergies">None</span>
<br>&nbsp;<br>
<span id="checkin-time" style="font-size: 11px">January 6th, 2017 04:48:07 pm</span></div>`

And my settings are as follows:
`{
      duplex: 'none',
      name:'label_' + ckid,
      printerId: sessionprinter,
      landscape: true,
      graystyle: true,
      hidePaperFormat: true,
      border: false,
      hidePageRange: true
}`

I'm using an iPad Pro running iOS 10.0.2 with a Brother QL-720NW label printer

![img_4518](https://cloud.githubusercontent.com/assets/2001665/21738615/3bcd4378-d43d-11e6-81a1-51a6ddd0d781.JPG)

**Comment by katzer** [comment]
@eugenedw You're not alone with the blank page issue but there's no fix yet.

**Comment by eugenedw** [comment]
The workaround that I've used is to generate this label as a PDF or BMP file. When I do, no blank labels appear.

**Comment by lasseron** [comment]
I'm having the same issue with Brother QL-820 printer. A blank page follows always to my content. Drives me crazy and the paper rolls for this printer are quite expensive too.

**Comment by lasseron** [comment]
Thank you for your help! I'm printing a group of HTML DOM elements with some inline CSS. Not sure I know how to create PDF from that using pure JavaScript.
