### ISSUE TITLE
WebView update seems to block preview & printing

### ISSUE THREAD

**Issue by wiffyb** [katzer/cordova-plugin-printer#121]
Hi,
we are using your printer plugin in an Ionic v1 app. It download a html page in javascript, and give it the print() function.
It was working fine the past year. 
But recently our phones been progressivly been updated and we isolate the Android System WebView. 

The App on the phones without update of this module, are still working.
The others have the following sympthomes : 
- when the printer service launch, it doesn't show the preview
- we still have 2 secondes to try to change to another printer
- but always fail
- even the save as a PDF... 
- it the show a "impossible to modify parameters" and freez
- some very rare times, it show a preview (for "hello world" or very simple content), but... when we click on the button to print,  it's gone and freeze again.

After some reading, i've found something about enableSlowWholeDocumentDraw, that could be a lead, but really don't know, i'm not an expert in those fields... 

ps : by the way, the printer is an HP, and use the HP printing service extension.

**Comment by katzer** [comment]
@wiffyb 
> phones been progressivly been updated and we isolate the Android System WebView.

Can you give me more details about what this means. What WebView do you use?

>  i've found something about enableSlowWholeDocumentDraw

Would you also share the page where you found it.

**Comment by wiffyb** [comment]
@katzer 

Your plugins use webview to pass the HTML and make the preview. 
The "Android System WebView" is installed on all Galaxy s4.

In our phone fleet, we have the ones with version 53.0 that are working fine with the plugins
and the ones with version 55.0 where the plugins dont work anymore... 

the information about the change (i don't know if it has any relevance) : https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorWebView

**Comment by mobidev111** [comment]
The error shown is:
> "Fehler beim Ändern der Einstellungen. Versuchen Sie es erneut."
> "Failed to change the settings. Try again."

Root cause: seems to be a bug in the Android System WebView.

issue for chromium: [link](https://bugs.chromium.org/p/chromium/issues/detail?id=664400&q=%22failed%20to%20change%20the%20settings%20try%20again%22&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

workaround: downgrade the webview - this indeed works, but is a suboptimal longterm solution.
> "We have got the investigate feedback from R&D team, they found this is a Google WebView issue. Here is the information from R&D: 
> temporary workaround. You can try to downgrade Android System WebView (reset it to a factory version). The following steps can be done on Galaxy phones for that: 
> ·         Go to Settings->Application manager 
> ·         Touch More button and select “Show system apps” 
> ·         Open Android System WebView 
> ·         Touch Disable button (and touch Disable or OK or Agree in each popup) 
> ·         Touch Enable button. 
> Also auto update of Android System WebView should be disabled (it can be done in Play Store app). 
https://productforums.google.com/forum/#!topic/chrome/vrFgtdBBWQ4

**Comment by wiffyb** [comment]
Thanks for those information.
We will try and let you know !
