### ISSUE TITLE
Issue with check on Android

### ISSUE THREAD

**Issue by skrpc** [katzer/cordova-plugin-printer#122]
Cordova version 6.4.0
Cordova platform Android@6.1.1
cordova-printer-plugin 0.7.3
Android versions 4.4.2 and  5.1

I have noticed that the avail value is blank in the callback function passed to check(), on editing the underlying code I see that this seems to be related to returning a list array of PluginResult.

If I change Printer.java to use

command.sendPluginResult(res1);

rather than

command.sendPluginResult(res);

i.e. send a single plugin result rather than an array the avail parameter is set as expected in the callback function albeit there is no count parameter.

Thanks for the work on an excellent plugin.

**Comment by gabaum10** [comment]
This is also happening for me.
