### ISSUE TITLE
Is there any way to print document.title or custom headers or footers ?

### ISSUE THREAD

**Issue by yogeshgadge** [katzer/cordova-plugin-printer#123]
My page spans multiple pages (unknown length). When printed from browser IE 11 I see that the page title (document.title) is repeated. But from cordova I don't see document.title printed at all.

**Comment by TheDeathStreaker** [comment]
That would be useful to know. Also could headers and footers contain some special tags to generate page numbers (preferably similar/same as jsreports {#pageNum} and {#numPages})

**Comment by katzer** [comment]
There's no support for.
