### ISSUE TITLE
How could I print canvas?

### ISSUE THREAD

**Issue by brunocollaco** [katzer/cordova-plugin-printer#124]
Hello, thank you for this plugin

Maybe this is a dumb question, but I wanna print some chart that is inside a canvas and has a ID.
However, I'm getting a blank page if I use: var obj = document.getElementById('myChart');
Is it possible to do that or should I look for another solution?

Thanks a lot.

**Comment by EionRobb** [comment]
Would you be better off converting the canvas to an image and printing the image instead?

**Comment by brunocollaco** [comment]
Oh, ok. I'll look for how to do it.

Thanks.

**Comment by brunocollaco** [comment]
Do you recommend any plugin to do that? I found this one: org.devgeeks.Canvas2ImagePlugin, but it is not supported anymore

Thanks a lot.

**Comment by brunocollaco** [comment]
Ok! It worked!
`    $scope.print = function(cnvs) {

        var canvas = document.getElementById(cnvs),
        ctx = canvas.getContext('2d');

        var image = canvas.toDataURL("image/png");
        var imgCode = '<img src="'+image+'"/>';

        var doc = "<html><body>TEST";
        doc = doc + "'" + imgCode + "'";
        doc = doc + "</body></html>";

        console.log(doc);

        if($cordovaPrinter.isAvailable()) {
            $cordovaPrinter.print(doc);
        } else {
            alert("Printing is not available on device");
        }
    }`

Cheers!
