### ISSUE TITLE
use same webview as Cordova app itself

### ISSUE THREAD

**Issue by TonivdW** [katzer/cordova-plugin-printer#126]
My app uses Crosswalk on Android and forces WKWebView on iOS to circumvent the webview issues on older devices. This printer plugin however seems to feed the HTML to the default webview on the device, resulting in a total rendering disaster on devices with an outdated default webview.
Is there any reason why this plugin can not use the same webview that is also used by the Cordova app itself?

**Comment by katzer** [comment]
Fixed with upcoming release
