### ISSUE TITLE
Unable to print QR code in Android

### ISSUE THREAD

**Issue by amalinaaziz** [katzer/cordova-plugin-printer#127]
I am unable to print a qr code in android, texts are displayed, only QR code not showing and it works fine in iOS. Anyone has a pointer on this issue?

> var myCanvas;
    function initCanvas(){
        myCanvas = document.getElementsByTagName("canvas");
		$('#qr').replaceWith('<img src="'+myCanvas[0].toDataURL("image/png")+'"/>');
    }
    window.addEventListener('load', initCanvas, false);

**Comment by amalinaaziz93** [comment]
anyone?

**Comment by katzer** [comment]
Must be because of the URL. Relative URLs should point to the www folder.
