### ISSUE TITLE
Print speeds on iOS (airprint)

### ISSUE THREAD

**Issue by ZzzenT** [katzer/cordova-plugin-printer#129]
I can see a big difference in print speeds when printing via airPrint (iOS) when printing directly (printToPrinter). And altering the printer reference by changing the hostname to its ip address. This speeds up printing tremendously. Guess the cause is related to a DNS resolve that needs to happen internally?

When you use printToPrinter and the reference to the printer (printer URL if you wish) hold a hostname it's just very slow (15-20 seconds). Changing that hostname to the ip address speeds up printing to a shocking 5-8 seconds)

This is all done using a Brother QL-720NW.

**Comment by samoka** [comment]
I'm having the exact same issue, how did you manage to change it to the ip address? the dialog only provides the url.

**Comment by ZzzenT** [comment]
@samoka by just using the ipaddress instead of a hostname in the parameter printerId, for example: ipp://x.x.x.x:631/ipp/print

Should speed up printing

**Comment by samoka** [comment]
Thanks will test this out.

**Comment by ZzzenT** [comment]
good luck
