### ISSUE TITLE
Not printing on zebra.android.zebrautilities

### ISSUE THREAD

**Issue by frivera77** [katzer/cordova-plugin-printer#13]
Hello! 
I'm trying to implement the plugin, did the following steps, but still don't print anything.

1) download zebra utilities from google play store. works fine.
2) from the demo app, I did connect the bluetooth printer and print a test page. works fine.
3) from the CLI:
cordova plugin add https://github.com/katzer/cordova-plugin-printer.git. works fine.
4) after deviceready event fires the window.plugin.printer.isServiceAvailable and returns me: com.zebra.android.zebrautilites. works fine.

function setupprinter()
{
    try
    {
        gPrinterIsAvailable = 0;
        window.plugin.printer.isServiceAvailable(
            function (isAvailable, installedAppIds)
            {
                //alert('The following print apps are installed on your device: ' + installedAppIds.join(', '));
                gPrintingServer = installedAppIds[0];
                gPrinterIsAvailable = 1;
            }
        );
    } catch (e) { notify(e.message); }
}

5) when a button is touched, execute the following function:

function printinvoice()
{
    try
{
        var strToPrint = "";
        strToPrint = "<html> "
        strToPrint = strToPrint + " <head><style>@media print "
        strToPrint = strToPrint + " {h1 {page-break-before:always;}} "
        strToPrint = strToPrint + " </style></head><body>Hola mundo</body></html> "
        if (gPrinterIsAvailable == 1)
        {
              alert('going to print...');
              window.plugin.printer.print(strToPrint);
        } else { notify("ERROR, Printer is unavailable."); }

```
} catch (e) { notify(e.message); }
```

}

6) nothing happen, didn't print and never goes to catch. 

Will appreciate any light on this.

**Comment by orenagiv** [comment]
Anyone found a solution to this one? (printing to a Zebra printer)

**Comment by EionRobb** [comment]
Yeah use PrintHand instead
