### ISSUE TITLE
Support for Cordova Browser Platform

### ISSUE THREAD

**Issue by arcadius** [katzer/cordova-plugin-printer#131]
Hello.

Is there any plan to support the Cordova Browser Platform?
https://cordova.apache.org/announcements/2016/03/04/cordova-browser-4.1.0.html

Thanks

**Comment by artcouto92** [comment]
+1

**Comment by katzer** [comment]
I am planning to support browser platform via the print.js lib

**Comment by rogerthedeveloper** [comment]
Error: exec proxy not found for :: Printer :: print
Is compatible? with Browser?
