### ISSUE TITLE
CSS page-break-after freezes print dialog in iOS

### ISSUE THREAD

**Issue by MikeSpencer42** [katzer/cordova-plugin-printer#137]
I recently updated my app's print styles to include a cover page by utilizing `page-break-after: always`. It turns out that this one line of code completely froze the print dialog and crashed the app. Error logs indicated that iOS was choking while determining the page count. I find this to be perplexing because the same CSS works correctly when printing from Safari in iOS.

In any case, it's best to avoid using `page-break-after`, but `page-break-before` and `page-break-inside` both seem to work fine.

**Comment by EionRobb** [comment]
We have the same issue, but for us the workaround was removing margins

**Comment by gs2589** [comment]
Im having the same issue on chrome when trying to print. Im working on web, not iOS.  How would I inspect error logs for the print dialog?

**Comment by katzer** [comment]
The plugin just sends the content to the printer. The printer itself is responsible for the rendering and for the proper support of CSS.
