### ISSUE TITLE
"cordova run android" not work

### ISSUE THREAD

**Issue by Samyssmile** [katzer/cordova-plugin-printer#139]
Hello
after clone i  use cordova run android

"\AndroidManifest.xml:13:9-205 Error:
        Element activity#de.appplant.cordova.plugin.printer.ui.SelectPrinterActivity at AndroidManifest.xml:13:9-205 duplicated with element declared at AndroidManifest.xml:12:9-200
C:\Users\xxxx\Downloads\cordova-plugin-printer\platforms\android\AndroidManifest.xml Error:
        Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output."

---------------
How to fix it?

**Comment by katzer** [comment]
Should not be a problem anymore. Also with the upcoming release the activity does not exist anymore.
