### ISSUE TITLE
Cant find the printer

### ISSUE THREAD

**Issue by Yethroy** [katzer/cordova-plugin-printer#146]
I'm new in hybrid apps development. I develop app that require printing. I installed it on android POS device that have thermal printer embedded on device I failed to detect the printer. Every time I open this page it alert the unavailable message . Help please  here are my codes 

````
import { Component } from '@angular/core';
import { NavController, NavParams,AlertController } from 'ionic-angular';
import { Printer, PrintOptions } from '@ionic-native/printer';


@Component({
  selector: 'page-print',
  templateUrl: 'print.html',
})
export class PrintPage {

  constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    public alertCtrl: AlertController,
    public printer: Printer) {
    this.printer.isAvailable().then(value => {
      this.showAlert("isAvailable", value);

    }).catch(error => {
      this.showAlert("ERROR",error);
    });

  }


print(){
          this.printer.check().then(data=>{
            this.showAlert('Check',data);
            },error =>{
            this.showAlert('Check Failed',error);
          });
  }

  showAlert(title, message) {
    let alert = this.alertCtrl.create({
      title: title,
      subTitle: JSON.stringify(message),
      buttons: ['OK']
    });
    alert.present();
  }
}

```

**Comment by ymohammad** [comment]
Hi @Yethroy , I am also facing the same issue. Did you find any solution for this issue?

**Comment by Mathewsmusukuma** [comment]
Hey @Yethroy Did you manage to use an embedded printer? I am also facing the same problem

**Comment by uokivan** [comment]
@Yethroy @ymohammad @Mathewsmusukuma 
I am also facing the same problem
but I saw the ionic doc , this plugin need to do the following things:
1.isAvailable()
2.check()
3.pick()

but I also don't know how to make it.....

**Comment by katzer** [comment]
The plugin is not responsible to discover connected printer. The system is doing it. So if your printer is not in the list, then connect your printer with Android/iOS first by installing the printer service, ...
