### ISSUE TITLE
How to enable built-in printer for android POS

### ISSUE THREAD

**Issue by Yethroy** [katzer/cordova-plugin-printer#147]
I have Android Pos with built-in POS. I dont know how to print through my device's built in printer any one to help me on that. My issues is I cant see my installed printer.

**Comment by GregKapustin** [comment]
Hi @Yethroy have you any update on that ?

**Comment by katzer** [comment]
The plugin supports all printer as long as they are connected with the OS. The plugin uses the native printing API - it communicates the the OS and not directly with the printer.
