### ISSUE TITLE
can't use `@media print` to adjust css from mobile to print

### ISSUE THREAD

**Issue by chegeiser** [katzer/cordova-plugin-printer#148]
Often we want the printed document to look different than what shows on the mobile screen. To do this we use something like this:
```
@media print {
   @page {

  	  margin-left: 0.75in !important;
  	  margin-right: 0.75in !important;
  	  margin-top: 1in;
  	  margin-bottom: 1in;
    }
  .no-print, .no-print * {
  display: none !important;
    page-break-inside: avoid;
  }
}
```

This does not work with this plugin. Is there any other way to print a view other than the view showing on the mobile screen?

Thanks,
Che

**Comment by katzer** [comment]
The plugin is not responsible for the rendering process. It only sends the content. Blame the printer...
