### ISSUE TITLE
Can't able to print sample PDF

### ISSUE THREAD

**Issue by grandhisubrahmanyam35** [katzer/cordova-plugin-printer#150]
I am trying to print an simple PDF file, which suppose to access through an URL/API . For this, I written following code but it's work out.

`cordova.plugins.printer.print('http://che.org.il/wp-content/uploads/2016/12/pdf-sample.pdf', {name: 'Document.pdf'});`

Same code snippet working, when I try to print a web page like

`cordova.plugins.printer.print('https://www.w3schools.com/', {name: 'Document.pdf'});`

what went wrong, when I try to print an sample pdf which was accessed by URL/API.

**Comment by katzer** [comment]
These feature (PDF, images, Base64) has been added to the upcoming release for iOS and Android.
