### ISSUE TITLE
ionic - Is it posible to print the current page?

### ISSUE THREAD

**Issue by DetoloX** [katzer/cordova-plugin-printer#151]
I am working in ionic project, so, Is it posible to print the current page?

If I write location.href doesnt work..

**Comment by Charlywhat** [comment]
Have you tried this?

var page = document.body;
cordova.plugins.printer.print(page, 'CurrentPage.html');

**Comment by alexmod20** [comment]
Hi, I'm working with ionic too, but I have some problems with iOS devices.

First I've tried like you said, with document.body but it didn't work well.
Then I've tried with document.documentElement: the number of pages was correct but that were blank. 

I've include @media print css and work fine with other device or browser.

**Comment by nicks258** [comment]
@alexmod20  can you please provide sample code.

**Comment by katzer** [comment]
Its possible on master branch already. Just call `cordova.plugins.printer.print("")`.
