### ISSUE TITLE
Appgyver - Steroids: unable to build Android

### ISSUE THREAD

**Issue by gmaurano** [katzer/cordova-plugin-printer#152]
I have an issue while trying to build android app through Appgyver Cloud (the only way to make a build with Steroids framework is through their Cloud). 

I already used cordova-plugin-printer one year and a half ago without issues. 
I just put the plug in url in the settings panel, as described here:

http://docs.appgyver.com/tooling/build-service/plugins/configuring-custom-plugins/

If I try to add cordova-plugin-printer now, the Appgyver build system for Android run in error.
I had to fork the project, reset it to 0.7.1 version and then put my url in the Appgyver settings panel and it worked properly.

Below the build system error log:

Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Parallel execution with configuration on demand is an incubating feature.
WARNING [Project: :runtimes:StandaloneChromium] 'flavorDimension' will be removed by Android Gradle Plugin 2.0, it has been replaced by 'dimension'.
WARNING [Project: :runtimes:StandaloneChromium] 'flavorDimension' will be removed by Android Gradle Plugin 2.0, it has been replaced by 'dimension'.
WARNING [Project: :runtimes:StandaloneChromium] 'flavorDimension' will be removed by Android Gradle Plugin 2.0, it has been replaced by 'dimension'.
WARNING [Project: :runtimes:StandaloneChromium] 'flavorDimension' will be removed by Android Gradle Plugin 2.0, it has been replaced by 'dimension'.
:runtimes:StandaloneChromium:generateArm64DebugAndroidTestAssets
:modules:AGCordova:preBuild
:runtimes:StandaloneChromium:generateArm64DebugAndroidTestAssets UP-TO-DATE
:modules:AGCommonAssets:preBuild
:runtimes:StandaloneChromium:preBuild UP-TO-DATE
:modules:AGCommonAssets:preBuild UP-TO-DATE
:modules:AGCordova:preBuild UP-TO-DATE
:modules:AGWrapper:preBuild UP-TO-DATE
:modules:AGCommonAssets:preReleaseBuild
:runtimes:StandaloneChromium:preArm64DebugAndroidTestBuild
:modules:AGCommonAssets:preReleaseBuild UP-TO-DATE
:modules:AGWrapper:preReleaseBuild UP-TO-DATE
:runtimes:StandaloneChromium:preArm64DebugAndroidTestBuild UP-TO-DATE
:modules:AGCommonAssets:compileReleaseNdk
:modules:AGCordova:preReleaseBuild
:modules:AGCommonAssets:compileReleaseNdk UP-TO-DATE
:modules:AGCordova:preReleaseBuild UP-TO-DATE
:modules:AGWrapper:compileReleaseNdk
:runtimes:StandaloneChromium:prepareArm64DebugAndroidTestDependencies
:modules:AGWrapper:compileReleaseNdk UP-TO-DATE
:modules:AGCommonAssets:compileLint
:modules:AGCordova:compileReleaseNdk UP-TO-DATE
:modules:AGWrapper:compileLint
:runtimes:StandaloneChromium:mergeArm64DebugAndroidTestAssets
:modules:AGCordova:compileLint
:modules:AGCommonAssets:copyReleaseLint UP-TO-DATE
:modules:AGCordova:copyReleaseLint UP-TO-DATE
:modules:AGCommonAssets:mergeReleaseProguardFiles
:modules:AGCordova:checkReleaseManifest
:modules:AGWrapper:copyReleaseLint UP-TO-DATE
:modules:AGWrapper:checkReleaseManifest
:modules:AGCordova:preDebugAndroidTestBuild UP-TO-DATE
:modules:AGWrapper:preDebugAndroidTestBuild UP-TO-DATE
:modules:AGCordova:preDebugBuild UP-TO-DATE
:modules:AGWrapper:preDebugBuild UP-TO-DATE
:modules:AGCordova:preDebugUnitTestBuild UP-TO-DATE
:modules:AGWrapper:preDebugUnitTestBuild UP-TO-DATE
:modules:AGCordova:preReleaseUnitTestBuild
:modules:AGWrapper:preReleaseUnitTestBuild
:modules:AGCordova:preReleaseUnitTestBuild UP-TO-DATE
:modules:AGWrapper:preReleaseUnitTestBuild UP-TO-DATE
:modules:external:ImageGallery:library:preBuild UP-TO-DATE
:modules:external:ImageGallery:library:preReleaseBuild UP-TO-DATE
:modules:external:android-async-http:library:preBuild UP-TO-DATE
:modules:external:ImageGallery:library:compileReleaseNdk UP-TO-DATE
:modules:external:ImageGallery:library:compileLint
:modules:external:android-async-http:library:preReleaseBuild UP-TO-DATE
:modules:external:android-async-http:library:compileReleaseNdk UP-TO-DATE
:modules:external:ImageGallery:library:copyReleaseLint
:modules:external:android-async-http:library:compileLint
:modules:AGCommonAssets:packageReleaseRenderscript
:modules:external:ImageGallery:library:copyReleaseLint UP-TO-DATE
:modules:external:android-async-http:library:copyReleaseLint UP-TO-DATE
:modules:external:ImageGallery:library:checkReleaseManifest
:modules:external:ImageGallery:library:preDebugAndroidTestBuild UP-TO-DATE
:modules:external:ImageGallery:library:preDebugBuild UP-TO-DATE
:modules:external:ImageGallery:library:preDebugUnitTestBuild UP-TO-DATE
:modules:external:ImageGallery:library:preReleaseUnitTestBuild UP-TO-DATE
:modules:external:android-async-http:library:mergeReleaseProguardFiles
:modules:external:ImageGallery:library:prepareComAndroidSupportAppcompatV72301Library
:modules:AGCommonAssets:packageReleaseRenderscript UP-TO-DATE
:modules:AGCommonAssets:checkReleaseManifest
:modules:AGCommonAssets:prepareReleaseDependencies
:modules:AGCommonAssets:compileReleaseRenderscript
:modules:external:android-async-http:library:packageReleaseRenderscript UP-TO-DATE
:modules:external:android-async-http:library:checkReleaseManifest
:modules:external:android-async-http:library:prepareReleaseDependencies
:modules:external:android-async-http:library:compileReleaseRenderscript
:runtimes:StandaloneChromium:generateArm64DebugAssets UP-TO-DATE
:runtimes:StandaloneChromium:preArm64DebugBuild UP-TO-DATE
:runtimes:StandaloneChromium:checkArm64DebugManifest
:modules:external:pixate-freestyle-android:pixate-freestyle:preBuild UP-TO-DATE
:modules:external:pixate-freestyle-android:pixate-freestyle:preReleaseBuild UP-TO-DATE
:modules:external:pixate-freestyle-android:pixate-freestyle:compileReleaseNdk UP-TO-DATE
:modules:external:pixate-freestyle-android:pixate-freestyle:compileLint
:modules:external:pixate-freestyle-android:pixate-freestyle:copyReleaseLint UP-TO-DATE
:modules:external:pixate-freestyle-android:pixate-freestyle:mergeReleaseProguardFiles
:modules:external:pixate-freestyle-android:pixate-freestyle:packageReleaseRenderscript UP-TO-DATE
:modules:external:pixate-freestyle-android:pixate-freestyle:checkReleaseManifest
:modules:external:pixate-freestyle-android:pixate-freestyle:prepareReleaseDependencies
:modules:external:android-async-http:library:generateReleaseResValues
:modules:external:pixate-freestyle-android:pixate-freestyle:compileReleaseRenderscript
:modules:AGCommonAssets:generateReleaseResValues
:modules:AGCommonAssets:generateReleaseResources
:modules:AGCommonAssets:packageReleaseResources
:modules:external:android-async-http:library:generateReleaseResources
:modules:external:android-async-http:library:packageReleaseResources
:modules:external:android-async-http:library:compileReleaseAidl
:modules:AGCommonAssets:compileReleaseAidl
:modules:external:android-async-http:library:generateReleaseBuildConfig
:modules:AGCommonAssets:generateReleaseBuildConfig
:modules:AGCommonAssets:generateReleaseAssets UP-TO-DATE
:modules:AGCommonAssets:mergeReleaseAssets
:modules:external:pixate-freestyle-android:pixate-freestyle:generateReleaseResValues
:modules:external:android-async-http:library:generateReleaseAssets UP-TO-DATE
:modules:external:android-async-http:library:mergeReleaseAssets
:modules:external:pixate-freestyle-android:pixate-freestyle:generateReleaseResources
:modules:AGCommonAssets:processReleaseManifest
:modules:external:pixate-freestyle-android:pixate-freestyle:packageReleaseResources
:modules:external:android-async-http:library:processReleaseManifest
:modules:external:pixate-freestyle-android:pixate-freestyle:compileReleaseAidl
:modules:external:android-async-http:library:processReleaseResources
:modules:AGCommonAssets:processReleaseResources
:modules:external:pixate-freestyle-android:pixate-freestyle:generateReleaseBuildConfig
:modules:external:pixate-freestyle-android:pixate-freestyle:generateReleaseAssets UP-TO-DATE
:modules:external:pixate-freestyle-android:pixate-freestyle:mergeReleaseAssets
:modules:external:pixate-freestyle-android:pixate-freestyle:processReleaseManifest
:modules:external:pixate-freestyle-android:pixate-freestyle:processReleaseResources
:modules:external:android-async-http:library:generateReleaseSources
:modules:external:android-async-http:library:compileReleaseJavaWithJavac
:modules:AGCommonAssets:generateReleaseSources
:modules:AGCommonAssets:compileReleaseJavaWithJavac
:modules:external:pixate-freestyle-android:pixate-freestyle:generateReleaseSources
:modules:external:pixate-freestyle-android:pixate-freestyle:compileReleaseJavaWithJavac
:modules:external:ImageGallery:library:prepareComAndroidSupportPaletteV72301Library
:modules:AGCommonAssets:processReleaseJavaRes UP-TO-DATE
:modules:AGCommonAssets:transformResourcesWithMergeJavaResForRelease
:modules:AGCommonAssets:transformClassesAndResourcesWithSyncLibJarsForRelease
:modules:external:ImageGallery:library:prepareComAndroidSupportRecyclerviewV72301Library
:modules:AGCommonAssets:mergeReleaseJniLibFolders
:modules:AGCommonAssets:transformNative_libsWithMergeJniLibsForRelease
:modules:AGCommonAssets:transformNative_libsWithSyncJniLibsForRelease
:modules:AGCommonAssets:bundleRelease
:modules:external:ImageGallery:library:prepareComAndroidSupportSupportV42301Library
:modules:AGWrapper:generateReleaseBuildConfig
:modules:AGWrapper:generateReleaseAssets UP-TO-DATE
:modules:AGWrapper:generateReleaseResValues
:modules:AGWrapper:mergeReleaseProguardFiles
:modules:AGWrapper:packageReleaseRenderscript UP-TO-DATE
:modules:AGWrapper:processReleaseJavaRes UP-TO-DATE
:modules:AGWrapper:transformResourcesWithMergeJavaResForRelease
:modules:external:facebook-android-sdk:facebook:preBuild UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:preReleaseBuild UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:compileReleaseNdk UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:compileLint
:modules:external:facebook-android-sdk:facebook:copyReleaseLint UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:checkReleaseManifest
:modules:external:facebook-android-sdk:facebook:preDebugAndroidTestBuild UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:preDebugBuild UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:preDebugUnitTestBuild UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:preReleaseUnitTestBuild UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:prepareComAndroidSupportSupportV42000Library
:modules:external:facebook-android-sdk:facebook:prepareReleaseDependencies
:modules:external:facebook-android-sdk:facebook:compileReleaseAidl
:modules:external:ImageGallery:library:prepareReleaseDependencies
:modules:external:ImageGallery:library:compileReleaseAidl
:modules:external:facebook-android-sdk:facebook:compileReleaseRenderscript
:modules:external:facebook-android-sdk:facebook:generateReleaseBuildConfig
:modules:external:ImageGallery:library:compileReleaseRenderscript
:modules:external:facebook-android-sdk:facebook:generateReleaseAssets UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:mergeReleaseAssets
:modules:external:ImageGallery:library:generateReleaseBuildConfig
:modules:external:facebook-android-sdk:facebook:generateReleaseResValues
:modules:external:ImageGallery:library:generateReleaseAssets UP-TO-DATE
:modules:external:ImageGallery:library:mergeReleaseAssets
:modules:external:facebook-android-sdk:facebook:generateReleaseResources
:modules:external:facebook-android-sdk:facebook:mergeReleaseResources
:modules:external:ImageGallery:library:generateReleaseResValues
:modules:external:ImageGallery:library:generateReleaseResources
:modules:external:ImageGallery:library:mergeReleaseResources
:modules:external:facebook-android-sdk:facebook:processReleaseManifest
:modules:external:facebook-android-sdk:facebook:processReleaseResources
:modules:external:facebook-android-sdk:facebook:generateReleaseSources
:modules:external:facebook-android-sdk:facebook:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/administrator/app-builder/STAGING/client/modules/external/android-async-http/library/src/main/java/com/loopj/android/http/RequestParams.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:modules:external:android-async-http:library:processReleaseJavaRes UP-TO-DATE
:modules:external:android-async-http:library:transformResourcesWithMergeJavaResForRelease
:modules:external:android-async-http:library:transformClassesAndResourcesWithSyncLibJarsForRelease
:modules:external:android-async-http:library:mergeReleaseJniLibFolders
:modules:external:android-async-http:library:transformNative_libsWithMergeJniLibsForRelease
:modules:external:android-async-http:library:transformNative_libsWithSyncJniLibsForRelease
:modules:external:android-async-http:library:bundleRelease
:modules:AGCordova:generateReleaseBuildConfig
:modules:AGCordova:generateReleaseAssets UP-TO-DATE
:modules:AGCordova:generateReleaseResValues
:modules:AGCordova:mergeReleaseProguardFiles
:modules:AGCordova:packageReleaseRenderscript UP-TO-DATE
:modules:AGCordova:processReleaseJavaRes
:modules:AGCordova:transformResourcesWithMergeJavaResForRelease
:modules:AGStandalone:preBuild UP-TO-DATE
:modules:AGStandalone:preReleaseBuild UP-TO-DATE
:modules:AGStandalone:compileReleaseNdk UP-TO-DATE
:modules:AGStandalone:compileLint
:modules:AGStandalone:copyReleaseLint UP-TO-DATE
:modules:AGStandalone:checkReleaseManifest
:modules:AGStandalone:preDebugAndroidTestBuild UP-TO-DATE
:modules:AGStandalone:preDebugBuild UP-TO-DATE
:modules:AGStandalone:preDebugUnitTestBuild UP-TO-DATE
:modules:AGStandalone:preReleaseUnitTestBuild UP-TO-DATE
:modules:AGStandaloneAssets:preBuild UP-TO-DATE
:modules:AGStandaloneAssets:preReleaseBuild UP-TO-DATE
:modules:AGStandaloneAssets:compileReleaseNdk UP-TO-DATE
:modules:AGStandaloneAssets:compileLint
:modules:AGStandaloneAssets:copyReleaseLint UP-TO-DATE
:modules:AGStandaloneAssets:mergeReleaseProguardFiles
:modules:AGStandaloneAssets:packageReleaseRenderscript UP-TO-DATE
:modules:AGStandaloneAssets:checkReleaseManifest
:modules:AGStandaloneAssets:prepareReleaseDependencies
:modules:AGStandaloneAssets:compileReleaseRenderscript
:modules:AGStandaloneAssets:generateReleaseResValues
:modules:AGStandaloneAssets:generateReleaseResources
:modules:AGStandaloneAssets:packageReleaseResources
:modules:AGStandaloneAssets:compileReleaseAidl
:modules:AGStandaloneAssets:generateReleaseBuildConfig
:modules:AGStandaloneAssets:generateReleaseAssets UP-TO-DATE
:modules:AGStandaloneAssets:mergeReleaseAssets
:modules:AGStandaloneAssets:processReleaseManifest
:modules:external:ImageGallery:library:processReleaseManifest
:modules:AGStandaloneAssets:processReleaseResources
:modules:external:ImageGallery:library:processReleaseResources
:modules:AGStandaloneAssets:generateReleaseSources
:modules:AGStandaloneAssets:compileReleaseJavaWithJavac
:modules:AGStandaloneAssets:processReleaseJavaRes UP-TO-DATE
:modules:AGStandaloneAssets:transformResourcesWithMergeJavaResForRelease
:modules:AGStandaloneAssets:transformClassesAndResourcesWithSyncLibJarsForRelease
:modules:AGStandaloneAssets:mergeReleaseJniLibFolders
:modules:AGStandaloneAssets:transformNative_libsWithMergeJniLibsForRelease
:modules:AGStandaloneAssets:transformNative_libsWithSyncJniLibsForRelease
:modules:AGStandaloneAssets:bundleRelease
:modules:external:ImageGallery:library:generateReleaseSources
:modules:external:ImageGallery:library:compileReleaseJavaWithJavacNote: /Users/administrator/app-builder/STAGING/client/modules/external/ImageGallery/library/src/main/java/com/etiennelawlor/imagegallery/library/view/PaletteTransformation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:modules:external:ImageGallery:library:extractReleaseAnnotations
:modules:AGStandalone:generateReleaseBuildConfig
:modules:AGStandalone:generateReleaseAssets UP-TO-DATE
:modules:AGStandalone:generateReleaseResValues
:modules:AGStandalone:mergeReleaseProguardFiles
:modules:AGStandalone:packageReleaseRenderscript UP-TO-DATE
:modules:AGStandalone:processReleaseJavaRes UP-TO-DATE
:modules:AGStandalone:transformResourcesWithMergeJavaResForRelease
:modules:AGXWalkView:preBuild UP-TO-DATE
:modules:AGXWalkView:preReleaseBuild UP-TO-DATE
:modules:AGXWalkView:compileReleaseNdk UP-TO-DATE
:modules:AGXWalkView:compileLint
:modules:AGXWalkView:copyReleaseLint UP-TO-DATE
:modules:AGXWalkView:checkReleaseManifest
:modules:AGXWalkView:preDebugAndroidTestBuild UP-TO-DATE
:modules:AGXWalkView:preDebugBuild UP-TO-DATE
:modules:AGXWalkView:preDebugUnitTestBuild UP-TO-DATE
:modules:AGXWalkView:preReleaseUnitTestBuild UP-TO-DATE
:modules:AGXWalkView:generateReleaseBuildConfig
:modules:AGXWalkView:generateReleaseAssets UP-TO-DATE
:modules:AGXWalkView:generateReleaseResValues
:modules:AGXWalkView:mergeReleaseProguardFiles
:modules:AGXWalkView:packageReleaseRenderscript UP-TO-DATE
:modules:AGXWalkView:processReleaseJavaRes UP-TO-DATE
:modules:AGXWalkView:transformResourcesWithMergeJavaResForRelease
:runtimes:StandaloneChromium:preArm64ReleaseBuild UP-TO-DATE
:runtimes:StandaloneChromium:preArmDebugBuild UP-TO-DATE
:runtimes:StandaloneChromium:preArmReleaseBuild UP-TO-DATE
:runtimes:StandaloneChromium:preArm_and_x86DebugBuild UP-TO-DATE
:runtimes:StandaloneChromium:preArm_and_x86ReleaseBuild UP-TO-DATE
:runtimes:StandaloneChromium:preX86DebugBuild UP-TO-DATE
:runtimes:StandaloneChromium:preX86ReleaseBuild UP-TO-DATE
:runtimes:StandaloneChromium:generateArm64ReleaseAssets UP-TO-DATE
:runtimes:StandaloneChromium:checkArm64ReleaseManifest
:runtimes:StandaloneChromium:generateArmDebugAndroidTestAssets UP-TO-DATE
:runtimes:StandaloneChromium:preArmDebugAndroidTestBuild UP-TO-DATE
:runtimes:StandaloneChromium:prepareArmDebugAndroidTestDependencies
:runtimes:StandaloneChromium:mergeArmDebugAndroidTestAssets
:runtimes:StandaloneChromium:generateArmDebugAssets UP-TO-DATE
:runtimes:StandaloneChromium:checkArmDebugManifest
:runtimes:StandaloneChromium:generateArmReleaseAssets UP-TO-DATE
:runtimes:StandaloneChromium:checkArmReleaseManifest
:runtimes:StandaloneChromium:generateArm_and_x86DebugAndroidTestAssets UP-TO-DATE
:runtimes:StandaloneChromium:preArm_and_x86DebugAndroidTestBuild UP-TO-DATE
:runtimes:StandaloneChromium:prepareArm_and_x86DebugAndroidTestDependencies
:runtimes:StandaloneChromium:mergeArm_and_x86DebugAndroidTestAssets
:runtimes:StandaloneChromium:generateArm_and_x86DebugAssets UP-TO-DATE
:runtimes:StandaloneChromium:checkArm_and_x86DebugManifest
:runtimes:StandaloneChromium:generateArm_and_x86ReleaseAssets UP-TO-DATE
:runtimes:StandaloneChromium:checkArm_and_x86ReleaseManifest
:runtimes:StandaloneChromium:generateX86DebugAndroidTestAssets UP-TO-DATE
:runtimes:StandaloneChromium:preX86DebugAndroidTestBuild UP-TO-DATE
:runtimes:StandaloneChromium:prepareX86DebugAndroidTestDependencies
:runtimes:StandaloneChromium:mergeX86DebugAndroidTestAssets
:runtimes:StandaloneChromium:generateX86DebugAssets UP-TO-DATE
:runtimes:StandaloneChromium:checkX86DebugManifest
:runtimes:StandaloneChromium:generateX86ReleaseAssets UP-TO-DATE
:runtimes:StandaloneChromium:checkX86ReleaseManifest
:runtimes:StandaloneChromium:showProperties

BUILD PROPERTIES
================
minSdkVersion: 21
targetSdkVersion: 21
versionCode: 1813
versionName: 1.8.13
keystoreFilename: ../../../../STAGING/keys/keystore
keyAlias: hepvie
storePassword: (hidden)
keyPassword: (hidden)

:runtimes:StandaloneChromium:generateArmDebugBuildConfig
:runtimes:StandaloneChromium:generateArmDebugResValues
:runtimes:StandaloneChromium:compileArmDebugNdk UP-TO-DATE
:runtimes:StandaloneChromium:processArmDebugJavaRes UP-TO-DATE
:runtimes:StandaloneChromium:validateDebugSigning
:runtimes:StandaloneChromium:generateArmReleaseBuildConfig
:runtimes:StandaloneChromium:generateArmReleaseResValues
:runtimes:StandaloneChromium:compileArmReleaseNdk UP-TO-DATE
:runtimes:StandaloneChromium:processArmReleaseJavaRes UP-TO-DATE
:runtimes:StandaloneChromium:validateReleaseSigning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:modules:external:pixate-freestyle-android:pixate-freestyle:processReleaseJavaRes UP-TO-DATE
:modules:external:pixate-freestyle-android:pixate-freestyle:transformResourcesWithMergeJavaResForRelease
:modules:external:pixate-freestyle-android:pixate-freestyle:transformClassesAndResourcesWithSyncLibJarsForRelease
:modules:external:pixate-freestyle-android:pixate-freestyle:mergeReleaseJniLibFolders
:modules:external:pixate-freestyle-android:pixate-freestyle:transformNative_libsWithMergeJniLibsForRelease
:modules:external:pixate-freestyle-android:pixate-freestyle:transformNative_libsWithSyncJniLibsForRelease
:modules:external:pixate-freestyle-android:pixate-freestyle:bundleReleaseNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/administrator/app-builder/STAGING/client/modules/external/facebook-android-sdk/facebook/src/com/facebook/internal/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:modules:external:facebook-android-sdk:facebook:extractReleaseAnnotations
:modules:external:ImageGallery:library:mergeReleaseProguardFiles
:modules:external:ImageGallery:library:packageReleaseRenderscript UP-TO-DATE
:modules:external:ImageGallery:library:packageReleaseResources
:modules:external:ImageGallery:library:processReleaseJavaRes UP-TO-DATE
:modules:external:ImageGallery:library:transformResourcesWithMergeJavaResForRelease
:modules:external:ImageGallery:library:transformClassesAndResourcesWithSyncLibJarsForRelease
:modules:external:ImageGallery:library:mergeReleaseJniLibFolders
:modules:external:ImageGallery:library:transformNative_libsWithMergeJniLibsForRelease
:modules:external:ImageGallery:library:transformNative_libsWithSyncJniLibsForRelease
:modules:external:ImageGallery:library:bundleRelease
:modules:AGWrapper:prepareClientModulesAGCommonAssetsUnspecifiedLibrary
:modules:AGWrapper:prepareClientModulesExternalAndroidAsyncHttpLibraryUnspecifiedLibrary
:modules:AGWrapper:prepareClientModulesExternalImageGalleryLibraryUnspecifiedLibrary
:modules:AGWrapper:prepareClientModulesExternalPixateFreestyleAndroidPixateFreestyleUnspecifiedLibrary
:modules:AGWrapper:prepareCnPedantSweetalertLibrary13Library
:modules:AGWrapper:prepareComAndroidSupportAppcompatV72301Library
:modules:AGWrapper:prepareComAndroidSupportMultidex100Library
:modules:AGWrapper:prepareComAndroidSupportPaletteV72301Library
:modules:AGWrapper:prepareComAndroidSupportRecyclerviewV72301Library
:modules:AGWrapper:prepareComAndroidSupportSupportV42301Library
:modules:AGWrapper:prepareComGithubChrisbanesPhotoviewLibrary123Library
:modules:AGWrapper:prepareComPnikosisMaterialishProgress10Library
:modules:AGWrapper:prepareComVeinhornScrollgalleryviewLibrary103Library
:modules:AGWrapper:prepareReleaseDependencies
:modules:AGWrapper:compileReleaseAidl
:modules:AGWrapper:compileReleaseRenderscript
:modules:AGWrapper:mergeReleaseAssets
:modules:AGWrapper:generateReleaseResources
:modules:AGWrapper:mergeReleaseResources
:modules:AGWrapper:processReleaseManifest
:modules:AGWrapper:processReleaseResources
:modules:AGWrapper:generateReleaseSources
:modules:AGWrapper:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:modules:AGWrapper:extractReleaseAnnotations
:modules:external:facebook-android-sdk:facebook:mergeReleaseProguardFiles
:modules:external:facebook-android-sdk:facebook:packageReleaseRenderscript UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:packageReleaseResources
:modules:external:facebook-android-sdk:facebook:processReleaseJavaRes UP-TO-DATE
:modules:external:facebook-android-sdk:facebook:transformResourcesWithMergeJavaResForRelease
:modules:external:facebook-android-sdk:facebook:transformClassesAndResourcesWithSyncLibJarsForRelease
:modules:external:facebook-android-sdk:facebook:mergeReleaseJniLibFolders
:modules:external:facebook-android-sdk:facebook:transformNative_libsWithMergeJniLibsForRelease
:modules:external:facebook-android-sdk:facebook:transformNative_libsWithSyncJniLibsForRelease
:modules:external:facebook-android-sdk:facebook:bundleRelease
:modules:AGWrapper:packageReleaseResources
:modules:AGWrapper:transformClassesAndResourcesWithSyncLibJarsForRelease
:modules:AGWrapper:mergeReleaseJniLibFolders
:modules:AGWrapper:transformNative_libsWithMergeJniLibsForRelease
:modules:AGWrapper:transformNative_libsWithSyncJniLibsForRelease
:modules:AGWrapper:bundleRelease
:modules:AGCordova:prepareClientModulesAGCommonAssetsUnspecifiedLibrary
:modules:AGStandalone:prepareClientModulesAGCommonAssetsUnspecifiedLibrary
:modules:AGXWalkView:prepareClientModulesAGCommonAssetsUnspecifiedLibrary
:modules:AGXWalkView:prepareClientModulesAGWrapperUnspecifiedLibrary
:modules:AGStandalone:prepareClientModulesAGStandaloneAssetsUnspecifiedLibrary
:modules:AGCordova:prepareClientModulesAGWrapperUnspecifiedLibrary
:modules:AGXWalkView:prepareClientModulesExternalAndroidAsyncHttpLibraryUnspecifiedLibrary
:modules:AGCordova:prepareClientModulesExternalAndroidAsyncHttpLibraryUnspecifiedLibrary
:modules:AGXWalkView:prepareClientModulesExternalCrosswalkAndroidModuleUnspecifiedLibrary
:modules:AGCordova:prepareClientModulesExternalImageGalleryLibraryUnspecifiedLibrary
:modules:AGCordova:prepareClientModulesExternalPixateFreestyleAndroidPixateFreestyleUnspecifiedLibrary
:modules:AGCordova:prepareCnPedantSweetalertLibrary13Library
:modules:AGCordova:prepareComAndroidSupportAppcompatV72301Library
:modules:AGCordova:prepareComAndroidSupportMultidex100Library
:modules:AGStandalone:prepareClientModulesAGWrapperUnspecifiedLibrary
:modules:AGCordova:prepareComAndroidSupportPaletteV72301Library
:modules:AGCordova:prepareComAndroidSupportRecyclerviewV72301Library
:modules:AGCordova:prepareComAndroidSupportSupportV42301Library
:modules:AGCordova:prepareComFacebookAndroidFacebook3211Library
:modules:AGStandalone:prepareClientModulesExternalAndroidAsyncHttpLibraryUnspecifiedLibrary
:modules:AGStandalone:prepareClientModulesExternalImageGalleryLibraryUnspecifiedLibrary
:modules:AGStandalone:prepareClientModulesExternalPixateFreestyleAndroidPixateFreestyleUnspecifiedLibrary
:modules:AGStandalone:prepareCnPedantSweetalertLibrary13Library
:modules:AGCordova:prepareComGithubChrisbanesPhotoviewLibrary123Library
:modules:AGStandalone:prepareComAndroidSupportAppcompatV72301Library
:modules:AGCordova:prepareComPnikosisMaterialishProgress10Library
:modules:AGCordova:prepareComVeinhornScrollgalleryviewLibrary103Library
:modules:AGCordova:prepareReleaseDependencies
:modules:AGCordova:compileReleaseAidl
:modules:AGCordova:compileReleaseRenderscript
:modules:AGCordova:mergeReleaseAssets
:modules:AGCordova:generateReleaseResources
:modules:AGCordova:mergeReleaseResources
:modules:AGStandalone:prepareComAndroidSupportMultidex100Library
:modules:AGStandalone:prepareComAndroidSupportPaletteV72301Library
:modules:AGStandalone:prepareComAndroidSupportRecyclerviewV72301Library
:modules:AGStandalone:prepareComAndroidSupportSupportV42301Library
:modules:AGStandalone:prepareComGithubChrisbanesPhotoviewLibrary123Library
:modules:AGStandalone:prepareComPnikosisMaterialishProgress10Library
:modules:AGStandalone:prepareComVeinhornScrollgalleryviewLibrary103Library
:modules:AGStandalone:prepareReleaseDependencies
:modules:AGStandalone:compileReleaseAidl
:modules:AGStandalone:compileReleaseRenderscript
:modules:AGStandalone:mergeReleaseAssets
:modules:AGStandalone:generateReleaseResources
:modules:AGStandalone:mergeReleaseResources
:modules:AGCordova:processReleaseManifest
:modules:AGCordova:processReleaseResources
:modules:AGStandalone:processReleaseManifest
:modules:AGStandalone:processReleaseResources
:modules:AGXWalkView:prepareClientModulesExternalImageGalleryLibraryUnspecifiedLibrary
:modules:AGStandalone:generateReleaseSources
:modules:AGStandalone:compileReleaseJavaWithJavac
:modules:AGCordova:generateReleaseSources
:modules:AGCordova:compileReleaseJavaWithJavac
:modules:AGXWalkView:prepareClientModulesExternalPixateFreestyleAndroidPixateFreestyleUnspecifiedLibrary
:modules:AGXWalkView:prepareCnPedantSweetalertLibrary13Library
:modules:AGXWalkView:prepareComAndroidSupportAppcompatV72301Library
:modules:AGStandalone:extractReleaseAnnotations/Users/administrator/app-builder/STAGING/client/modules/AGCordova/src/de/appplant/cordova/plugin/printer/Printer.java:153: error: no suitable constructor found for PluginResult(Status,List<PluginResult>)
                PluginResult res  = new PluginResult(
                                    ^
    constructor PluginResult.PluginResult(Status,byte[],boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor PluginResult.PluginResult(Status,byte[]) is not applicable
      (actual argument List<PluginResult> cannot be converted to byte[] by method invocation conversion)
    constructor PluginResult.PluginResult(Status,boolean) is not applicable
      (actual argument List<PluginResult> cannot be converted to boolean by method invocation conversion)
    constructor PluginResult.PluginResult(Status,float) is not applicable
      (actual argument List<PluginResult> cannot be converted to float by method invocation conversion)
    constructor PluginResult.PluginResult(Status,int) is not applicable
      (actual argument List<PluginResult> cannot be converted to int by method invocation conversion)
    constructor PluginResult.PluginResult(Status,JSONObject) is not applicable
      (actual argument List<PluginResult> cannot be converted to JSONObject by method invocation conversion)
    constructor PluginResult.PluginResult(Status,JSONArray) is not applicable
      (actual argument List<PluginResult> cannot be converted to JSONArray by method invocation conversion)
    constructor PluginResult.PluginResult(Status,String) is not applicable
      (actual argument List<PluginResult> cannot be converted to String by method invocation conversion)
    constructor PluginResult.PluginResult(Status) is not applicable
      (actual and formal argument lists differ in length)
/Users/administrator/app-builder/STAGING/client/modules/AGCordova/src/de/appplant/cordova/plugin/printer/Printer.java:336: error: cannot find symbol
        super.pluginInitialize();
             ^
  symbol: method pluginInitialize()
/Users/administrator/app-builder/STAGING/client/modules/AGCordova/src/de/appplant/cordova/plugin/printer/Printer.java:334: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors

:modules:AGCordova:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:AGCordova:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 54.113 secs

**Comment by Jasphine** [comment]
Hi,

I have the same issue as well. Thanks and appreciate for your response.

**Comment by katzer** [comment]
I think your cordova-android platform is outdated. At least not supported version based on the trace.
