### ISSUE TITLE
0.7.4 - Fix for Android N

### ISSUE THREAD

**Issue by DSchau** [katzer/cordova-plugin-printer#153]
Hello!

First of all, thanks for the great plugin. We have been using it in our Android/iOS application for quite some time, and have really enjoyed using it.

That said, I noticed that 0.7.4 is currently staged for release, and it contains a fix for Android printing in Android N. I also validated this fix on my device, so that's encouraging!

However, just wondering when it's planned to roll out/release 0.7.4? Please let me know if I can help with anything!

**Comment by joeyemery** [comment]
Also desperate to know when this is going to be released, we need it before our application can launch.

@DSchau How did you manage to validate it works, is there a way to access the development builds?

**Comment by DSchau** [comment]
@joeyemery you can just use the Github master branch as a source, rather than something published to NPM

To do that:

`cordova plugin add https://github.com/katzer/cordova-plugin-printer --save`

which will save the master branch as a dep and write to config.xml.

**Comment by joeyemery** [comment]
@DSchau Thanks very much, worked wonders!

**Comment by katzer** [comment]
I wasn't aware about honestly that I didn't release the fixes until now. However I am planing to release v0.8 once I am done with the updates.
