### ISSUE TITLE
Extra blank page printed 

### ISSUE THREAD

**Issue by smuthu01** [katzer/cordova-plugin-printer#154]
We using printer plugin to print PDF. For some reason it always adding extra one page.
I have used all setting but it not working. Is there any specific setting i need to set in UIPrintInteractionController?

Thanks,
Muthu.S

**Comment by lj222kj** [comment]
@smuthu01 which printer(hardware) are you using?

**Comment by smuthu01** [comment]
We are using iOS10.x and using air print. 
Devices are iPod and iPadmini.

Thanks,
Muthu.S

**Comment by smuthu01** [comment]
I set border false then i started to work properly.
