### ISSUE TITLE
How can I change the Label Printer Page Size.

### ISSUE THREAD

**Issue by radhemad** [katzer/cordova-plugin-printer#155]
I'm trying to print Labels and Receipt on the same Printer Brother QL720NW. It always cuts Receipt too at the Label length.

It can be fixed by either Cutting the Label at the end or by Increasing the page size (Length) of current Printing item.

Can some one help how to fix this.

**Comment by Masjidat** [comment]
hello,
 You got this fixed? I am also in need of this code.

thanks

**Comment by aleehpandita** [comment]
Did you find a solution ?

**Comment by lasseron** [comment]
I'm having the same question as well.

**Comment by ubahnverleih** [comment]
For iOS i created a PR, where you can configure the cutting length on iOS: https://github.com/katzer/cordova-plugin-printer/pull/185

**Comment by katzer** [comment]
I've merged the PR - thanks for it!
