### ISSUE TITLE
print to  default printer 

### ISSUE THREAD

**Issue by engmohammad224** [katzer/cordova-plugin-printer#161]
I need to print directly from my app to a specific printer , I don't need to show a printet page ,
can I ???

**Comment by engmohammad224** [comment]
print a default printer

**Comment by katzer** [comment]
For iOS you can specify the printer (printerId). If its a correct network URL then no dialog will popup.

**Comment by BadiuAlexandru** [comment]
For Android is any way to achieve this?

**Comment by katzer** [comment]
not via Android Printing Framework. Only if you use the 3rd party SDK for the printer.

**Comment by jsitu** [comment]
@katzer can I grab the network URL when I select a printer from the popup? The issue I ran into is the app could not locate the correct default printer automatically, and we can't predefine the network URL beforehand, will have to save the printer URL once a user selects it from the list.
