### ISSUE TITLE
Check printer always returns no services

### ISSUE THREAD

**Issue by sachinranaorem** [katzer/cordova-plugin-printer#165]
I tried this plugin, but on checking the printing services in the android it always returns none services. Can you please let me know what wrong am i doing with the code.

------Here is my code ------------

var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function() {
	
		
		cordova.plugins.printer.check(function (avail, count) {
			alert(avail ? 'Found ' + count + ' services' : 'No');
			
		
		});
		
		
        app.receivedEvent('deviceready');
    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
};

**Comment by saichaitanyaeruvaram** [comment]
Any solution to this? I am also facing the same problem.
#179

**Comment by brassier** [comment]
I'm seeing the same.  I've got 3 printer services running on my android device, and can print manually.  The calls to `isAvailable()` and `check()` return no services, unfortunately.

**Comment by ostrichegret** [comment]
me too, i already install PrintHead and PrinterShare but still cannot found any.

**Comment by katzer** [comment]
The functions have been removed for upcoming release - closing it
