### ISSUE TITLE
Is this plugin work for Brother Label Printer...?

### ISSUE THREAD

**Issue by chetuBhadra93** [katzer/cordova-plugin-printer#167]
Hello,
I have Brother Printer, And i want to print label using ionic application.
So please let me know this printer will able to print from Brother's printer or not.

Thanks in advance.

**Comment by NgYueHong** [comment]
You might want to look at this: https://github.com/gordol/cordova-brother-label-printer

**Comment by sagrawal31** [comment]
Yes, it works amazingly

**Comment by tester12345678910111213** [comment]
I would beg to differ, there doesn't seem to be a way to set the label size.

**Comment by ubahnverleih** [comment]
I created a PR, which let you set the size of the label on rollprinters, at least on iOS: https://github.com/katzer/cordova-plugin-printer/pull/185

**Comment by BadiuAlexandru** [comment]
It is possible to print directly from the app? without making the printer selection and selecting manually the printer landscape and size?

**Comment by katzer** [comment]
Yes, but only for iOS if you specify the network URL of the printer.
