### ISSUE TITLE
Pick Does Not Work for iOS, ionic 3, Angular 4.x+

### ISSUE THREAD

**Issue by eugenedw** [katzer/cordova-plugin-printer#169]
When calling the printer.pick method, the APPPrinter.m class method fails since options are expected, but none are passed.

```
    NSMutableDictionary* settings = [arguments objectAtIndex:0];
    NSArray* bounds = [settings objectForKey:@"bounds"];
```

(the settings are "null" here).

The decorator associated with the typescript resource for the plugin doesn't allow options to be provided and, subsequently, the option merge returns undefined for the params:

`params = this.mergeWithDefaults(params);
`

I can implement a workaround so that the plugin.js "mergeWithDefaults" returns the defaults when none are passed or an empty object when an empty object is passed in, but this seems like a hack.

The Angular typescript decorator needs to be changed to allow options. I'd submit a pull request for this, but the source isn't available (as far as I see).

**Comment by nicks258** [comment]
Did you find a solution for this? @eugenedw @kentongray @janpio @nehresma

**Comment by janpio** [comment]
(Mentioning random people that have not appeared in an issue before is pretty impolite. Please refrain from doing so to get attention to your question. Thank you.)

**Comment by raceyi** [comment]
I have the same issue. Would you share your workaround solution?

**Comment by daniel7912** [comment]
@eugenedw thanks for this, your pull request helped me fix the issue too. After editing the `printer.js` file, I had to run:

`ionic cordova platform rm ios`
`ionic cordova platform add ios`

to make the changes take effect.
