### ISSUE TITLE
Same html code but different pdf generated in IOS and android

### ISSUE THREAD

**Issue by ppbntl19** [katzer/cordova-plugin-printer#171]
I am not using custom setting just doing some HTML with the standard default setting.
In chrome, Android print preview looks same but On IOS it looks different.
I am not sure why? :)
Maybe because of Android  (Google print service) ad IOS (Air Print)  using different printing service and they render differently.
`cordova.plugins.printer.print(pdf_html, htmlFileName, function () {});`
For Android
![image](https://user-images.githubusercontent.com/11989749/36964189-dd187b2c-207b-11e8-97b5-1a1bbeb30ae2.png)
For IOS
![image](https://user-images.githubusercontent.com/11989749/36964225-f5a1a13c-207b-11e8-8de2-75e0e3ecb1a7.png)

**Comment by katzer** [comment]
Different rendering engine... With the upcoming release you can print pdf files. So it might look identically.
