### ISSUE TITLE
Not Able to Open PDF files Using HTTP PDF URL or Local filesystem Urls | Android

### ISSUE THREAD

**Issue by rachitpsolanki** [katzer/cordova-plugin-printer#173]
I am using Ionic and cordova printer pdf plugin, If I try to print a pdf using print() in Android it open a black page, In ios it renders the page as expected to print.

Code sample

	this.printer.isAvailable().then(() => {
		let filePath = "file:///storage/emulated/0/Download/" + filename;
		this.printer.print(filePath, {name:filename}).then(() => {
			alert('printer opened')
		}, () => {
			alert('printer failed to load')

		});
	}, () => {
		alert('Printer not available');
	});

**Comment by katzer** [comment]
These feature has been added. Just wait for the next release.
