### ISSUE TITLE
Path of script or style in the html file needed to print ?

### ISSUE THREAD

**Issue by EngMohammadAbdullah** [katzer/cordova-plugin-printer#174]
how to load the scripts and stylesheets in html file which i need to print . 
for  example : 
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
this link is working in  a page , but when i copy code to plugin , path not working 

   var str = '<html xmlns="http://www.w3.org/1999/xhtml"><head> <script src="jquery.min.js"></script> <script src="bootstrap.min.js"></script> <link href="../css/bootstrap.min.css" rel="stylesheet" /> <style> body { background: rgb(204,204,204); } page { background: white; display: block; margin: 0 auto; margin-bottom: 0.5cm; box-shadow: 0 0 0.5cm rgba(0,0,0,0.5); } page[size="A4"] { width: 21cm; height: 29.7cm; } page[size="A4"][layout="portrait"] { width: 29.7cm; height: 21cm; } page[size="A3"] { width: 29.7cm; height: 42cm; } page[size="A3"][layout="portrait"] { width: 42cm; height: 29.7cm; } page[size="A5"] { width: 14.8cm; height: 21cm; } page[size="A5"][layout="portrait"] { width: 21cm; height: 14.8cm; } @media print { body, page { margin: 0; box-shadow: 0; } } .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th { padding-left: 30px; border-left: .5px solid #000000; } .table > caption + thead > tr:first-child > td, .table > caption + thead > tr:first-child > th, .table > colgroup + thead > tr:first-child > td, .table > colgroup + thead > tr:first-child > th, .table > thead:first-child > tr:first-child > td, .table > thead:first-child > tr:first-child > th { text-align: center; border-left: 0; } #tt div { float: left; clear: none; margin-left: 10px } </style></head><body> <page size="A4"> <table class="table"> <thead> <tr> <th>العمود الأول</th> <th>العمود الثاني</th> </tr> </thead> <tbody> <tr> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> </tr> <tr> <td>Cell 3</td> <td>Cell 2</td> </tr> <tr> <td>Cell 1</td> <td>Cell 2</td> </tr> <tr> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> </tr> <tr> <td>Cell 3</td> <td>Cell 2</td> </tr> <tr> <td>Cell 1</td> <td>Cell 2</td> </tr> <tr> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> </tr> <tr> <td>Cell 3</td> <td>Cell 2</td> </tr> <tr> <td>Cell 1</td> <td>Cell 2</td> </tr> <tr> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> </tr> <tr> <td>Cell 3</td> <td>Cell 2</td> </tr> <tr> <td>Cell 1</td> <td>Cell 2</td> </tr> <tr> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> </tr> <tr> <td>Cell 3</td> <td>Cell 2</td> </tr> <tr> <td>Cell 1</td> <td>Cell 2</td> </tr> <tr> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> </tr> <tr> <td>Cell 3</td> <td>Cell 2</td> </tr> <tr> <td>Cell 1</td> <td>Cell 2</td> </tr> <tr> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> </tr> <tr> <td>Cell 3</td> <td>Cell 2</td> </tr> <tr> <td>Cell 1</td> <td>Cell 2</td> </tr> <tr> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> <td> <div id="tt"> <div id="yy">First</div> <div>Second</div> </div> </td> </tr> <tr> <td>Cell 3</td> <td>Cell 2</td> </tr> <tr> <td>Cell 1</td> <td>Cell 2</td> </tr> </tbody> </table> </page></body></html>';

                cordova.plugins.printer.print(str, {
                    printerId: "MG3600 series(192.168.0.206)",

                });

script and stylesheets not working

**Comment by katzer** [comment]
Usually the path should be relative from your www folder (iOS)
