### ISSUE TITLE
Unable to pick up orientation

### ISSUE THREAD

**Issue by natezeevo** [katzer/cordova-plugin-printer#176]
In my app I have a PDF that can be printed. Because the content of these PDFs can change on a regular basis, they are not cached on the app but printed directly from a URL (server within the network).

Some of these are landscape, some are portrait. Setting the default orientation one way or another isn't going to cut it here. I found an old closed ticket that suggested setting the orientation to null to allow it to work it out at the print end which hasn't worked either.

The only other setting that I am passing is border: false otherwise the pages also go from one full-page print to a page-and-a-bit.

Can someone please assist with this?

**Comment by katzer** [comment]
With the new release simply don't specify the orientation and the system will automatically choose the best.
