### ISSUE TITLE
Printer is not work in IPhone

### ISSUE THREAD

**Issue by vinayak-dataman** [katzer/cordova-plugin-printer#177]
Hi 

I have integrated the plugin that is working fine in Android. But not work in IPhone. In IPhone it work strange.
I click on button to print. It is not launch. when I click on status bar again or come foreground from background then It opens the printer page. 

Please suggest what I am doing wrong. I am stuck from a long time on this issue.

```
print(){

  this.printer.isAvailable().then((onSuccess=>{}), onerror=>{});
  this.printer.check().then((onSuccess=>{}), onerror=>{});
  let options: PrintOptions = {
    name: 'MyDocument',
    duplex: true,
    landscape: true,
    grayscale: true
  };
  let printData = this.printContent(); 
  setTimeout(() => {

  
  this.platform.ready().then(success =>{
   
  this.printer.print(printData).then(function()
  {
   
  },
  function()
  {
     alert("Error while printing!");
  });

  },
  error=>{
    alert('Platform Not Ready'+error);
  });
  }, 100);
  
  
}
```

**Comment by yefrioscar** [comment]
You forget put options like that:

let options: PrintOptions = {
    name: 'MyDocument',
    duplex: true,
    landscape: true,
    grayscale: true
  };

 this.printer.print(printData, options).then(...)

**Comment by vinayak-dataman** [comment]
It behaviour also same with options

**Comment by katzer** [comment]
Any error? Cannot reproduce.
