### ISSUE TITLE
Android 8.1.1 - cordova.plugins.printer.pick and cordova.plugins.printer.check is not working 

### ISSUE THREAD

**Issue by saichaitanyaeruvaram** [katzer/cordova-plugin-printer#179]
**Environment**

* Printer is wifi printer - HP DeskJet Series

* RedMi A1 - Android 8.1.1
* Moto G5 plus - Android 8.1.1

Tried **cordova plugin add cordova-plugin-printer** and **cordova plugin add https://github.com/katzer/cordova-plugin-printer.git**

**cordova.plugins.printer.print** -  opens the choose printer dialogue and after selecting printer, print is coming out

**Bug**
**cordova.plugins.printer.pick** - it is not returning any printers
**cordova.plugins.printer.check** - it is returning 0

**Comment by katzer** [comment]
I've removed all these code and reorganises how it works on Android. Closing it. Wait for the upcoming release.
