### ISSUE TITLE
Ionic HTML tags don't render in the Print preview, whereas plain HTML does

### ISSUE THREAD

**Issue by matthew2564** [katzer/cordova-plugin-printer#183]
I have installed the Ionic 3 printer and am attempting to print part of my application.
https://ionicframework.com/docs/native/printer/

     this.printer.isAvailable().then(() => {
        let printContent = document.getElementById('printMe');
        let options: PrintOptions = {landscape: false, grayscale: true};

        this.printer.print(printContent, options).then(() => {
          // success
        }, error => {
         // handle error
        });
      }, error => {
        // handle error
      });

This allows me to launch the Print Options menu while on a device or simulator (iOS). However, the Ionic content on the device has a different output whilst in Print Preview and subsequently the physical print itself.

This is my output from using Ionic html tags:- 

![screen shot 2018-06-25 at 2 24 56 pm](https://user-images.githubusercontent.com/33056264/41853219-33829608-7885-11e8-8c41-0c347690a8c6.png)

Plain HTML on the other hand looks the same in application and during print preview.

Has anyone come across my issue? And if so, did you manage to make any progress?

Thanks!

**Comment by kirtipriya** [comment]
I face the same issue , ionic tags are not rendered properly.
I am using the ionic printer plugin.
@matthew2564 did you find a solution for this ?

**Comment by matthew2564** [comment]
@kirtipriya my understanding is that the printer plugin takes the inner html. So if you wrote the page you're trying to print in plain html with inline styling that should render more like how you expect. However i ended up using PDFMake, and combining it with this plugin to print.

**Comment by kirtipriya** [comment]
Ok ,so combining pdf make with the printer plugin , helped in rendering the ionic styling  properly ? The styling is not inline in my case , external stylesheet is used.

**Comment by matthew2564** [comment]
So PDFMake is basically a way to write templates in JSON (http://pdfmake.org/playground.html). I used the output of this to pass into the print function of this plugin, and it renders exactly as intended.

**Comment by tzgued** [comment]
> So PDFMake is basically a way to write templates in JSON (http://pdfmake.org/playground.html). I used the output of this to pass into the print function of this plugin, and it renders exactly as intended.

I really need this, I already wasted a lot of time. Can you please recall what exactly you did ? I did something like this and did seem to work I get an empty page.


`
            this.pdfObj = pdfMake.createPdf(docDefinition);
            this.pdfObj.getDataUrl((dataUrl) => {
                const targetElement = (document.querySelector('#iframeContainer')) as HTMLElement;
                const iframe = document.createElement('iframe');
                iframe.src = dataUrl;
                targetElement.appendChild(iframe);

                let options: PrintOptions = {
                    name: 'MyDocument',
                    duplex: true,
                    orientation: 'landscape',
                    monochrome: true
                }

                this.printer.print(targetElement, options).then(() => {
                    console.log('yes');
                }, err => {
                    console.log(err)
                });
            });
`

**Comment by matthew2564** [comment]
@tzgued Hi there, let me try and give you a basic example of how I implemented it.

`import { Platform } from 'ionic-angular';`
`import { File } from '@ionic-native/file';`
`import { Printer } from '@ionic-native/printer';`


 // first define the doc def
`const documentDefinition = getDocumentDefinition();`

// pass the documentDefinition to pdfMake
`const pdfObj = pdfMake.createPdf(documentDefinition);`

// use the pdfObj to create print template
```
 if (!this.platform.is('cordova')) {
      pdfObj.print();
    } else {
      pdfObj.getBuffer(async (buffer) => {
        const blob = new Blob([buffer], { type: 'application/pdf' });
        const fileName = 'someNameHere.pdf';
        await this.file.writeFile(this.file.dataDirectory, fileName, blob, { replace: true });
        await this.printer.print(this.file.dataDirectory + fileName);
      });
    }
```

Assuming your document definition is setup correctly then you should be good to go!

**Comment by tzgued** [comment]
@matthew2564 Believe it or not I tried this combination before and it didn't work, now it did can't remember what I've done wrong the first time. but yes the document definition was correct I succeeded to open the file with a pdf reader and then print it.

Anyway thanks man
