### ISSUE TITLE
Print function in ionic 3

### ISSUE THREAD

**Issue by KishanIos007** [katzer/cordova-plugin-printer#189]
Hello,

I am using PDFMake for creating the pdf with my predefined Document definition. In my old ionic 1 project I am passing encoded string to `print` function which works fine. here is the code for old ionic 1 

```
var dd = $scope.createDocumentDefinition();
            $timeout(function () {
                var pdf = pdfMake.createPdf(dd);
                pdf.getBase64(function (encodedString) {
                    console.log(encodedString);
                    $ionicLoading.hide();
                    window.plugins.PrintPDF.print({
                        data: encodedString,
                        type: 'Data',
                        title: 'Print Document',
                        success: function () {
                            console.log('success');
                        },
                        error: function (data) {
                            data = JSON.parse(data);
                            console.log('failed: ' + data.error);
                        }
                    });
                });
            }, 1000);
```
Now I am upgrading my project to Ionic 3 so I tried same thing but output is different here is my new ionic 3 code . printer open but instead of printing as per my document definition it just print the encoded string.

```
let printer_ = this.printer;
    var dd = this.createDocumentDefinition();
    var pdf = pdfMake.createPdf(dd);
    pdf.getBase64(function (_encodedString) {
      let options: PrintOptions = {
        name: 'MyDocument'
      };
      console.log(JSON.stringify(pdf));
      printer_.print(_encodedString, options).then((msg)=>{
        console.log("Success",msg);
      },(error)  => {
        console.log("Error", error);
      });
      });
```
  
Any idea how to use this in ionic 3 ??

**Comment by KishanIos007** [comment]
@katzer please help me out

**Comment by KishanIos007** [comment]
@katzer Please help me out

**Comment by KishanIos007** [comment]
Look here https://github.com/bpampuch/pdfmake/issues/1464 , they say that "pdfmake library is for generate pdf files; not for html or other, for this use different library." Since your plugin is in official documentation of ionic , plugin should support input as one of these threes(base64, buffer or blob).

**Comment by KishanIos007** [comment]
@kentongray @janpio @nehresma @nkjf5 @ErikWallin can u please look into this.

**Comment by janpio** [comment]
No and mentioning random people is highly inappropriate. 
Feel free to hire someone for money, then you can just call them with whatever problem you have.

**Comment by KishanIos007** [comment]
You are one of the contributor and I thought you can help me on this that's why I mention you here my friend and Its not always about money :) we all are here for helping each other If you can't just ignore.

Have a nice day

**Comment by janpio** [comment]
I am a random person that did 1 README change in this project. I am also not your friend.
Just accept that mentioning random people in Github issues not appropriate and back down.

**Comment by KishanIos007** [comment]
I didn't know what you commit OK and this is totally too rude the way you talk. Fine this is not the place for discussion. I accept, happy now ? Does this makes you feel happy then fine I don't have any issue.

**Comment by uokivan** [comment]
@KishanIos007 did u fix it now ? or use other plugin ?

**Comment by katzer** [comment]
The ionic wrapper might not be up to date but the feature to print PDF files has been added (currently in dev branch). Just wait for the next release.

**Comment by selmo47** [comment]
Waiting excitely for the new release.
You can now use : [https://github.com/sarahgoldman/cordova-print-pdf-plugin/](url)
