### ISSUE TITLE
Printing to "(null)"

### ISSUE THREAD

**Issue by Wolrab1** [katzer/cordova-plugin-printer#191]
Why is this plugin still being recommended on Ionic Native when no support is being given? 

I have installed this plugin and followed the instructions, I am passing a printerID but I get the pop up:

> Printing to "(null)"
> Failed to Contact Printer

**I have two questions:**

1) Why is this pop up a thing, can we disable
2) Is there a way to specify an ip address of the printer we want to connect to

**Comment by Kev1n337** [comment]
You can specify an network URL in PrintOptions.

```
this.printer.print(content, {printerId: 'networkURL'})
```

When you add an invalid value there, you'll get the described error "printing to "(null)". When you don't specify a value at all, you'll be redirected to the default AirPrint view, where you can search for printers. (Same for android).

You can find more options to add in the official [docs](https://ionicframework.com/docs/native/printer/)

**Comment by katzer** [comment]
It means that the printer you've specified does not exist.

**Comment by jsitu** [comment]
@katzer can we capture the printer network URL when it's selected from the list?
