### ISSUE TITLE
API compatibility error on Android 9 - usage of now greylisted API, leads to user-facing error

### ISSUE THREAD

**Issue by mobidev111** [katzer/cordova-plugin-printer#198]
An error message appears when printing on Android 9:
```
Detected problems with API compatibility (visit g.co/dev/appcompat for more info)
```

This error message is user-facing, i.e., can't be turned of by the developer.

Google deprecated some APIs for public use in Android 9 - Android 8 and below still fine.

The specific log messages are:
```
Accessing hidden method Landroid/print/PrintManager;->addPrintJobStateChangeListener(Landroid/print/PrintManager$PrintJobStateChangeListener;)V (light greylist, reflection)
```
```
Accessing hidden method Landroid/print/PrintManager;->getPrintJob(Landroid/print/PrintJobId;)Landroid/print/PrintJob; (dark greylist, reflection)
```

This means, the usage of PrintManager. addPrintJobStateChangeListener() and PrintManager.getPrintJob() needs to be reworked.

**Comment by katzer** [comment]
I've removed all these code and reorganises how it works on Android. Closing it. Wait for the upcoming release.
