### ISSUE TITLE
Printer not found fix for Android N and above causes earlier versions to still fail

### ISSUE THREAD

**Issue by p10petr** [katzer/cordova-plugin-printer#199]
@katzer Hello, relating to this https://github.com/katzer/cordova-plugin-printer/issues/165, I recently had an issue with the printer.check(available,count) not finding any printers and I used your dev branch to fix it for android > N. Since I am building my project for different-versioned devices (Android 7.0  and Android 8.0.0 to be exact), that fix also causes the earlier versions (or at least my Android 7.0) to not find any printers. Could this be in fact an issue from your changes or my Android 7.0 device not having a Printer subsystem installed?
(I am also using Cordova's InAppBrowser plugin, dunno if that's relevant or not)

**Comment by katzer** [comment]
I've removed all these code and reorganises how it works on Android. Closing it. Wait for the upcoming release.

**Comment by paulearnest** [comment]
@katzer May I know whether the new code has the fix as I see the issue still. Thank You
