### ISSUE TITLE
Error on Cordova Build  ( PGB)

### ISSUE THREAD

**Issue by ebofi** [katzer/cordova-plugin-printer#200]
Hi,

We are getting a Probs error while building the app. Its was triggered from your plugin, Kindly check this .

Exact Log from PGB

:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/src/de/appplant/cordova/plugin/printer/Printer.java:295: error: local variable props is accessed from within inner class; needs to be declared final
                do_print(webView, props);
                                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.279 secs
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/src/de/appplant/cordova/plugin/printer/Printer.java:295: error: local variable props is accessed from within inner class; needs to be declared final
                do_print(webView, props);
                                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by katzer** [comment]
I've removed all these code and reorganises how it works on Android. Closing it. Wait for the upcoming release.

**Comment by ebofi** [comment]
ok

**Comment by ebofi** [comment]
Do you have date for the upcomming release...

**Comment by katzer** [comment]
Basically its ready, only the README is still the old one. Thats why its in the dev branch. Need to find the time to update the docs before I can release it.
