### ISSUE TITLE
On Dev Branch - PGB Error

### ISSUE THREAD

**Issue by ebofi** [katzer/cordova-plugin-printer#202]
Hi Mate,

Thanks for the wonderful work ..

And today i tried to build a app using your DEV branch and PhoneGap Cloud Build service endeded with below error.

HERE IS OUR CONFIG.XML ENTRIES
===========================
    <preference name="android-minSdkVersion" value="19" />
    <preference name="android-targetSdkVersion" value="28" />
    <preference name="phonegap-version" value="cli-7.1.0" /> 

PHONEGAP ERROR LOG
==================
Total time: 3.599 secs
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/src/de/appplant/cordova/plugin/printer/PrintManager.java:183: error: lambda expressions are not supported in -source 1.6
        ((Activity) context).runOnUiThread(() -> {
                                              ^
  (use -source 8 or higher to enable lambda expressions)
/src/de/appplant/cordova/plugin/printer/Printer.java:91: error: lambda expressions are not supported in -source 1.6
        cordova.getThreadPool().execute(() -> {
                                           ^
  (use -source 8 or higher to enable lambda expressions)
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by katzer** [comment]
You have to upgrade your source compatibility level to Java 1.7 or even better 1.8

**Comment by ebofi** [comment]
> You have to upgrade your source compatibility level to Java 1.7 or even better 1.8

Can we know how we can do that .. any examples on the same

**Comment by BodduSatya** [comment]
Hello Katzer,

i too have the same issue with pgb failure.

any fix?
