### ISSUE TITLE
Error on calling print on Android 8

### ISSUE THREAD

**Issue by jsjunior** [katzer/cordova-plugin-printer#203]
Hi.

First, thanks a lot for your great work.

I'm trying to use your plugin in a Vue/Capacitor app (Android) but, when I call the print method, like this:
```
let page = document.getElementById('ticket')

window.cordova.plugins.printer.print(page, 'Document.html')
```

, I'm getting this error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
        at de.appplant.cordova.plugin.printer.Printer.loadContent(Printer.java:209)
        at de.appplant.cordova.plugin.printer.Printer.access$500(Printer.java:64)
        at de.appplant.cordova.plugin.printer.Printer$3.run(Printer.java:181)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

Also tried to get dev version working without success. Could anyone kindly help? Thanks in advance!

**Comment by katzer** [comment]
If you use the dev branch, please see the readme. The way you pass the arguments worked in the past, but not now anymore.

**Comment by jsjunior** [comment]
I couldn't manage to get the dev branch to work. I'm using the v0.7.3.

**Comment by katzer** [comment]
Whats the issue?
> I couldn't manage to get the dev branch to work.

**Comment by jsjunior** [comment]
> ```
> E/AndroidRuntime: FATAL EXCEPTION: main
>     java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
>         at de.appplant.cordova.plugin.printer.Printer.loadContent(Printer.java:209)
>         at de.appplant.cordova.plugin.printer.Printer.access$500(Printer.java:64)
>         at de.appplant.cordova.plugin.printer.Printer$3.run(Printer.java:181)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6626)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
> ```

**Comment by jsjunior** [comment]
I've cloned from dev, installed with npm (because my app isn't a Cordova app) from clone and, when trying to build in Android Studio, a lot of errors came. Started with a "lambda expression is not supported at this language level 7" (what I managed to solve) but, every try to build, new errors were rised and insisted with the v0.7.3 what got me the error in first post.

**Comment by jsjunior** [comment]
Terrible sorry. I was trying print a HTML fragment with an image. Realized that I was doind it wrong. After create a page to display the content needed and pass this url to plugin, worked like a charm in v0.7.3.

Thanks and appologies for this and again thank you for your work!

PS: I've closed this issue.
