### ISSUE TITLE
[DEV BRANCH] PDF - mark/reset not supported

### ISSUE THREAD

**Issue by dimitriadamou** [katzer/cordova-plugin-printer#204]
Hey there,

I have tried the Print update on the Dev branch, when printing PDFs on android I get `mark/reset` not supporter

To get around this I modified `printer/PrintManager.java`
```
        InputStream stream    = PrintContent.open(path, context);
```
to
```
        BufferedInputStream stream    = new BufferedInputStream(PrintContent.open(path, context));
```
Which seems to of fixed that, however the new error is `Resetting to invalid mark` - so the Input Stream probably needs to be re-created.

Commenting out `input.reset();`#239 in PrintContent.java resolves the issue anyhow.

Thanks for the updates btw!

**Comment by katzer** [comment]
Fixed
