### ISSUE TITLE
It prints the HTML code

### ISSUE THREAD

**Issue by iyasilias** [katzer/cordova-plugin-printer#225]
I am using your plugin to print a page from url

```
    this.backend.get(url).subscribe(res => {
      this.printer.print(res, options).then(() => {
        console.log('success print');
      }, () => {
        console.log('fail print');
      });
```

But it turns out that it will print the HTML code. See below 
![WhatsApp Image 2019-09-19 at 12 19 56 PM](https://user-images.githubusercontent.com/634151/65213229-f123f480-dad7-11e9-94de-967e0327dce3.jpeg)

I tried convert the page into a base64 string, but it won't appear even in preview.

**code to convert to base64**
```
  toDataUrl(url, callback) {
    const xhr = new XMLHttpRequest();
    xhr.onload = () => {
      const reader = new FileReader();
      reader.onloadend = () => {
        callback(reader.result);
      };
      reader.readAsDataURL(xhr.response);
    };
    xhr.open('GET', url);
    xhr.responseType = 'blob';
    xhr.send();
  }
```

```
    this.toDataUrl(url, (res) => {
      this.printer.print('base64://' + res.split(',')[1], options).then(() => {
        console.log('success print');
      }, () => {
        console.log('fail print');
      });
    });
```

The resulting base64 seems to work, but I cannot print it.

So my problem is that it cannot print the dom from url, and it cannot print the base64 string which I convert from the dom.

**Comment by iKarl** [comment]
Hi,

A literal valid string of HTML is:

`// Valid!
strHTML  = '< strong>Hola | Hello</ strong>< br />< strong>Adios | Bey</ strong>';

// Invalid
strHTML  = '< strong>Hola|Hello</ strong>
     < br />
< strong>Adios | Bey</ strong>'; 

this.printer.print(strHTML, options).then(() => {
   console.log('success print');
}, () => {
   console.log('fail print');
});
`
Try delete: \r, \n, \t before to pass function print.

This fixed for me.

Sorry for my English

**Comment by iyasilias** [comment]
Thanks for your tips. It seems the error comes from the empty first line.. 

**before (problem)**
```
1
2 <html>
```

**after (success)**
```
1 <html>
2
```
