### ISSUE TITLE
At the end print a blank page in iOS 8

### ISSUE THREAD

**Issue by JMarqz** [katzer/cordova-plugin-printer#24]
First at all, this is a really great plugin!
I know that iOS 8 its very new. But I just want make you know about this bug.

I'm using Phonegap Build to use this plugin. And I've tested in iOS 6, iOS 7 and iOS 8.0.2, and works great, but just in iOS 8 at the end print a blank page. It's not a big deal, but can be fixed.

**Comment by katzer** [comment]
Cannot find a way to cut the last page. Testing with simulated printers a blank page gets added on printers with duplex.

**Comment by h-morales** [comment]
This code works for me.
No excess paper.

`      cordova.plugins.printer.print(
        htmlContent, 
        {
          name: 'printjob',
          printerId: printerUrl, // ipp://192.168.##.##/printer
          //duplex: false, // even if this is false, it still set to 1 in xcode. remove it!
          landscape: false, 
          graystyle: true, 
          hidePaperFormat: true,
          border: false,
          hidePageRange: true
        },
          function(msg) {console.log('ok: ' + msg)},
          function(msg) {alert('error: ' + msg)}
        );`
