### ISSUE TITLE
Specifying page size?

### ISSUE THREAD

**Issue by alanmontgomery** [katzer/cordova-plugin-printer#251]
Hey,

I'm using this plugin in conjunction with a mobile printer: 
https://www.zebra.com/content/dam/zebra_new_ia/en-us/solutions-verticals/product/Printers/Mobile%20Printers/ZQ500%20Series%20Mobile%20Printers/zq500-general/spec-sheets/zq500-series-spec-sheet-en-us.pdf

The print specifications for this is 10.4CM Wide as seen on page 5 of the above document.

In order to force the print popup to appear this size how can I achieve this? Or will it automatically force that size? I am currently only testing on a desktop printer.

Here are my options;

`var LocalPrintOptions = {
        name: "NoticeReceipt",
        printerId: 'printer007',
        duplex: 'none',
        landscape: false,
        grayscale: false,
        maxWidth: "10.4cm",
        paper: {
            width: "10.4cm"
        },
        font: {
            align: "center"
        },
        pageCount: 1
    };`

Am I right to put the 10.4cm into paper.width and maxWidth? This limits the size of the actual content on the print preview (as well as the printed document) - How can I force the actual paper size though? Or is this inherited from the connected / selected printer? E.g. I'm using my desktop printer for testing and it's by default an A4 printer obviously?

Thanks,

Alan

**Comment by darwin4416** [comment]
Did it worked on mobile printer?
