### ISSUE TITLE
Cordova print plugin does not print google web fonts

### ISSUE THREAD

**Issue by sniras** [katzer/cordova-plugin-printer#37]
Google web fonts used in the app display correctly inside the cordova app. However when the app page (or a div on the page) is printed using this cordova print plugin , the web fonts do not display and revert to the browser default font. Is there a solution or workaround to this problem? Thanks in advance.

**Comment by katzer** [comment]
I think not because Android print view can only render a limited HTML subset (RTF) and a custom font face isn't supported.
