### ISSUE TITLE
App crashes when trying to print

### ISSUE THREAD

**Issue by RonCan** [katzer/cordova-plugin-printer#41]
I have attached a screenshot from my logcat.
var page = '<h1>Hello Document</h1>';

cordova.plugins.printer.print(page, 'index.html', function () {
    alert('printing finished or canceled')
});

I'm using this code to print. index.html is the page that I have in my application but I couldn't see any reason for this name to be required even though I'm just trying to print a string. Can you help?
Thanks
![screenshot from 2015-02-02 03 44 19](https://cloud.githubusercontent.com/assets/4863594/5994256/df7ab856-aa8d-11e4-9b8b-2ad0815eebe8.png)

**Comment by katzer** [comment]
See #28 (not yet)

**Comment by lobobobo** [comment]
Install your plugins removing older plugin...It worked for me.. ;-)

**Comment by bmwertman** [comment]
@lobobobo can you share some more detail on your solution? I'm having the same issue.

**Comment by bmwertman** [comment]
I'm using this in an application with a (sails.js)[http://sailsjs.org/] backend. If I install from master it breaks the websocket functionality built into sails which I'm depending on. Likewise if I remove the plugin completely, websockets break. With the plugin installed using `cordova plugin add de.appplant.cordova.plugin.printer` my websockets work but the app crashes when the `print` function gets called.

**Comment by lobobobo** [comment]
cordova plugin add https://github.com/katzer/cordova-plugin-printer.git


Use above plugin removing your older plugin
