### ISSUE TITLE
IOS - printing w/o dialog

### ISSUE THREAD

**Issue by ZzzenT** [katzer/cordova-plugin-printer#42]
Should it be possible to print w/o the airprint dialog (should be possible since IOS 8 from what I've read?) using the options (json object: { printerId: 'printername' } ?

I keep getting the dialog even though I specify the printerId.

**Comment by katzer** [comment]
Have fixed that. `printerId` now accepts the network URL of a printer.

**Comment by ZzzenT** [comment]
Does this mean there also NO dialog when you specify a network URL of a printer?

**Comment by katzer** [comment]
>Does this mean there also NO dialog when you specify a network URL of a printer?

Yes

**Comment by 1nstinct** [comment]
Seems it doesn't work on IOS 14. Printing like this `cordova.plugins.printer.print(content, { printer: 'ipps://Canon001b88.local.:443/ipp/print' })` still shows me a review popup and doesn't print until I press Print button.

**Comment by savageqm** [comment]
Is there a way to prevent the dialog that says "Printing to xxx" from showing also when using url as the printerId?

**Comment by ZzzenT** [comment]
The printer reference should be 'ipp://...'

Kind regards,

Steven

**Comment by savageqm** [comment]
any way of preventing that printing progress dialog from appearing?

**Comment by ZzzenT** [comment]
Don’t think so, since its the OS forcing it upon us.Let me know should you ever find out how, would be interested in that as well.StevenOn 31 Jan 2023, at 19:24, Vladimir Castillo ***@***.***> wrote:﻿
any way of preventing that printing progress dialog from appearing?
