### ISSUE TITLE
iOS 8.2 update breaks plugin

### ISSUE THREAD

**Issue by jmsaavedra** [katzer/cordova-plugin-printer#43]
Since updating my devices to 8.2, this plugin fails to bring up the Printer Options dialog. 

Services are available when checking, but no Print Dialog and failure after ~8 seconds of waiting.  Still works on 8.1 for me.

Anyone else experiencing this?

**Comment by borrull** [comment]
Same here with the plugin installed via 'cordova plugin install', but this was fixed in https://github.com/katzer/cordova-plugin-printer/issues/26
