### ISSUE TITLE
Border in CSS

### ISSUE THREAD

**Issue by henriquels25** [katzer/cordova-plugin-printer#44]
I have a table with borders set in the columns (tr) but the borders are not printed in my document. In the application, the borders are displayed.

Also, the background is not properly printed in the PDF.

In the image htmlGenerated, it is possible to see the correct version, that is shown in the browser and in the mobile application. In the pdfGenerated.png, you can see the printed document with problems.

Is there a way to print the borders in the PDF?

.trHeader {
                    vertical-align: middle;
                    text-align: center;
                    border-style: solid;
                    border-width: 1px;
                    background: #DDD9C4;
                }

 <table style="margin-left: 5px; ">
                <tr class="trHeader">
                    <td style="width: 25%">
                    <img src="img/smallExample.png">
                    </td>

                    <td class="tdHeader">
                    <span> EXAMPLE </span>
                    </td>
                    <td style="width: 25%">
                    <img src="img/example2.png">
                    </td>
                </tr>

![pdfgenerated](https://cloud.githubusercontent.com/assets/4086440/6847758/9afba148-d3a7-11e4-8905-e843b25e4fbb.png)
![htmlgenerated](https://cloud.githubusercontent.com/assets/4086440/6847759/9b064684-d3a7-11e4-99de-1084db6ef933.png)

**Comment by katzer** [comment]
@henriquels25, the plugin does not render the HTML content. Cannot tell you why the web view does not render the border.
