### ISSUE TITLE
Version 0.7.0 for Phonegap Build

### ISSUE THREAD

**Issue by jvwelzen** [katzer/cordova-plugin-printer#45]
Any idea when this version 0.7.0 is released for phonegap build, it now says that this version is not compatible, and I realy need to print an external webpage (pdf) or generated html

**Comment by jvwelzen** [comment]
already found a solution to use the latest version :-)

using the new plugins.cordova.io option in PGB :-)

But is it possible to select the kind of paper (chosePaper delegate)

**Comment by katzer** [comment]
Yes v0.7 and v0.8 will become available on PGB too.

Specifying the kind of paper isn't supported yet.
