### ISSUE TITLE
Script prints empty page after first print

### ISSUE THREAD

**Issue by phbergsmann** [katzer/cordova-plugin-printer#46]
When I pre-set the printer-ID I can print the content once, but when I want to print some other content in the same Script the page is empty.

I'm using iOS 8.3, a Brother QL-720NW (it's the same behavior with the printer simulator) and IPP for the connection

**Comment by katzer** [comment]
@phbergsmann I've tested now with printer simulator and its been working. Please re-open if still existent as I am working on a new release. Thanks!
