### ISSUE TITLE
No Print preview in Android for Remote PDF files

### ISSUE THREAD

**Issue by Dineshrajaa** [katzer/cordova-plugin-printer#50]
Hello,
 I have tried using this plugin example and changed the file name to a remote PDF file but there is no print preview and even if i try printing an empty sheet is coming out of my printer ,but instead if I try using an remote XML file its shown in the print preview.
Is there anyway to print remote PDF files using this plugin??

**Comment by multilexus** [comment]
You could save the remove file locally first (using another plugin) and then print it using this plugin.

**Comment by katzer** [comment]
@Dineshrajaa Basically the plugin renders HTML content and sent that to the printer.
