### ISSUE TITLE
Method isAvailable seem not work

### ISSUE THREAD

**Issue by veasna234** [katzer/cordova-plugin-printer#51]
Hello everybody , I am new to phone gap development and plugin.
I have follow the instruction of cordova-plugin-printer , 
After install plugin by CLI and add <gap:plugin name="de.appplant.cordova.plugin.printer" />
to my file config xml. after that
I have add method
```javascript
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() { 
		    alert("ready");
			cordova.plugins.printer.isAvailable(function (available) {
                  alert(available); 
			});
		}
```
to my index page.
I noted that document.addEventListener is work normally.
but 
cordova.plugins.printer.isAvailable method seem not work.
I think I have follow all step of instruction

But still can not print page or just alert message

So anybody can tell me what I am doing wrong?

and So for my bad English.

**Comment by katzer** [comment]
@veasna234 Guess you found in the meantime already what happened. If not open the issue again.
