### ISSUE TITLE
cordova.plugins.printer not work

### ISSUE THREAD

**Issue by veasna234** [katzer/cordova-plugin-printer#52]
Hello everybody. I am new to phonegap and plugin.
i try to use katzer plugin printer. and start from install plugin 
then i put this code to my index
			document.addEventListener('deviceready', function () {
    // cordova.plugins.printer is now available
	    alert("ready");
	    cordova.plugins.printer.isAvailable(
			function (isAvailable) {
				alert(isAvailable ? 'Service is available' : 'Service NOT available');
			}
		);
		}, false);
   
it alert ready but it don't alert  isAvailable.
i can not find out why it do not alert. any one can tell me why ?
I think follow all step from 
https://github.com/katzer/cordova-plugin-printer

**Comment by katzer** [comment]
@veasna234 So far I cannot see the mistake. Guess you fixed it in the meantime. Sometimes the platform gets broken and its wise to re-add the whole platform from zero.
