### ISSUE TITLE
Image not displaying when I save to google drive v0.6.2

### ISSUE THREAD

**Issue by CrankyMero** [katzer/cordova-plugin-printer#53]
I had to use the version 0.6.2 due to some devices still have Android 4.2.2 and version 0.7.1 crashed the app, but well my main issue is the the form that i use export great except that it doesn't export the banner image that i need

the html tag containing the image is the following
![image](https://cloud.githubusercontent.com/assets/6289721/7991133/c93c794e-0aaa-11e5-9da3-953defef1a72.png)

When i see the form it displays it correctly but when i try to save the pdf from my app it doenst

v 0.6.2 on the left | v 0.7.1 on the right
![no image](https://cloud.githubusercontent.com/assets/6289721/7991047/1cdfdd08-0aaa-11e5-8eee-7388addcf001.JPG)

Doest anyone know a workaround to get that image displayed on version 0.6.2

thanks for your time

**Comment by CrankyMero** [comment]
I managed to fix this by adding a base64 image directly to the html like so

<div style="background-color:#f18b21;width:98%; margin-top:1%;margin-left:1%; margin-right:1%; "><img src="data:image/png;base64,HERE GOES THE BASE64 DATA" height="110" width="100%"/></div>

**Comment by katzer** [comment]
great!
