### ISSUE TITLE
Printer callback "OK" even when cancelled

### ISSUE THREAD

**Issue by thisdyingsoul** [katzer/cordova-plugin-printer#54]
When the printer command call the printer screen to confirm the print, if you press the return button and cancel the print it still return "OK" on the printer function callback.

**Comment by katzer** [comment]
@thisdyingsoul That has been added now 43c325317ab60177cdd8b544f1f3aee3877794e1

**Comment by golontico** [comment]
> @thisdyingsoul That has been added now [43c3253](https://github.com/katzer/cordova-plugin-printer/commit/43c325317ab60177cdd8b544f1f3aee3877794e1)

Same here the in android when press back  return always true..... i need help with it because after print run a service.. them always runs the servive : (
