### ISSUE TITLE
Get available printers list

### ISSUE THREAD

**Issue by gaikwad411** [katzer/cordova-plugin-printer#56]
Hi, 

    I am using this plugin in my cordova app.
  I have checked the earlier issues and readme, but did not get what I was looking for.

 I have requirement that **I need to display list of available printers on app**, so I will keep the id of one of the printer in local storage and at time of print I will use this id as argument to "print" function.

 **Is this possible using this plugin?** am I looking at wrong place?

Please help, thanks in advance.

**Comment by samoka** [comment]
@gaikwad411 Did you manage to find an alternative? Im also looking for this functionality.

**Comment by katzer** [comment]
@gaikwad411, @samoka that has been added for Android. The callback of the `isAvailable` methods contains an array with all installed and enabled printer services.

**Comment by samoka** [comment]
@katzer Thank you for this. And for iOS?
