### ISSUE TITLE
Printer bluetooth?

### ISSUE THREAD

**Issue by danicarla** [katzer/cordova-plugin-printer#57]
How i can use this plugin to print a ticket in Printer bluetooth?

**Comment by rodrigo-mesquita** [comment]
Olá Dani Carla

**Comment by rodrigo-mesquita** [comment]
Gostaria de saber, se vc conseguiu fazer impressão através do intel xdk pelo bluetooth. 
Gostaria de pedir sua ajuda, estou tentando fazer imprimir também.
Grato Rodrigo Mesquita

**Comment by danicarla** [comment]
@rodrigo-mesquita 
Consegui imprimir, mas é muito limitado.. não consegui nem colocar em negrito...

**Comment by rodrigo-mesquita** [comment]
Olá Dani, obrigado pela resposta, você poderia me ajudar, de que forma e qual plugin?
fico muito agradecido.
meu email rodrigomesquita95254798@gmail.com

**Comment by elewin** [comment]
This feature would be very nice to have

**Comment by katzer** [comment]
@danicarla The answer for your question is YES. Android Print Framework support Bluetooth Connection. Check the document here: https://developer.android.com/about/versions/android-4.4.html

But you need your printer's manufacturer to support Bluetooth too to print via Bluetooth.
