### ISSUE TITLE
Page break issue on iOS

### ISSUE THREAD

**Issue by pirvudoru** [katzer/cordova-plugin-printer#58]
Hi,

while I was debugging a print issue on iOS I noticed that event the most basic html that uses page breaks doesn't work properly. I even tried the html example from the readme page
```
<p>
First page.
</p>

<p style="page-break-before: always">
Second page.
</p>
```
and the result was a document with 3 pages as can be seen [here]( https://www.dropbox.com/s/jqq3cstpl40yqpj/result.pdf?dl=0). I'm not sure if this is an issue with the plugin or the printer driver or something else. Can you please confirm that printing the sample html works on an iPad 2?

**Comment by katzer** [comment]
@pirvudoru Theres an updated sample using lots of css and the preview shoes only one page. Depend on paper size its possible to be splittend across multiple pages.
