### ISSUE TITLE
how i can get the path wher the pdf is saved in case of printing as pdf ?

### ISSUE THREAD

**Issue by hatimox** [katzer/cordova-plugin-printer#62]
how i can get the path wher the pdf is saved in case of printing as pdf ?

**Comment by katzer** [comment]
Thats not possible since normal printer print out paper sheets.

**Comment by EionRobb** [comment]
I've got a modified version of the android print plugin that'll print to PDF, if that helps https://github.com/EionRobb/phonegap-print-plugins/blob/master/Android/PrintPDFPlugin.java
