### ISSUE TITLE
undefined is not an object (evaluating 'cordova.plugins.printer')

### ISSUE THREAD

**Issue by bariza** [katzer/cordova-plugin-printer#63]
I have followed the installation instructions and have this in index.html:

    <script src="lib/ngCordova/dist/ng-cordova.js"></script>
    <script src="cordova.js"></script>

Here is my controller call:

    $scope.printTable = function(){
    $ionicPlatform.ready(function() {
    cordova.plugins.printer.isAvailable(
        function (isAvailable) {
            alert(isAvailable ? 'Service is available' : 'Service NOT available');
        });
     })
    };

i get this error on phonegap app:

Error: undefined is not an object (evaluating 'cordova.plugins.printer')
I have this added in my config.xml file:

    <gap:plugin name="de.appplant.cordova.plugin.printer" version="0.7.0" />
What am i missing here

**Comment by katzer** [comment]
@bariza Not sure what was your problem but I guess you fixed it. Adding plugins with `cordova plugin add` is the recommended way.
