### ISSUE TITLE
share pdf insted of downloading  

### ISSUE THREAD

**Issue by manojrejinthala** [katzer/cordova-plugin-printer#66]

**Comment by manojrejinthala** [comment]
instead of downloading as a PDF i want to generate PDF while sharing via social media

**Comment by manojrejinthala** [comment]
i want to cretae one pdf and insert data into that pdf and share that pdf it should not download into the device.please provide any solutions for that.
thanks in advance 

regards
manoj

**Comment by katzer** [comment]
@manojrejinthala Sounds like you added that issue to the wrong plugin. That the plugin for printing HTML stuff.
