### ISSUE TITLE
In Emulator it works, not via ionic view

### ISSUE THREAD

**Issue by Jaspur** [katzer/cordova-plugin-printer#67]
Hi,
Emulator it's all working, not when I open it on a real iPhone. Looks like an error somewhere, because the {{ }}-tags are also visible like that instead of rendered. But I don't know how to debug that. On bottom of config.xml it has ```<plugin name="de.appplant.cordova.plugin.printer" spec="https://github.com/katzer/cordova-plugin-printer.git"/>```

**Comment by ydhif** [comment]
Hi,

I have the same problem. Everything's fine with the emulaor and nothing with my phone
