### ISSUE TITLE
Possible issue with cordova-ios 4.0.x

### ISSUE THREAD

**Issue by brodybits** [katzer/cordova-plugin-printer#68]
Someone reported an issue in litehelpers/Cordova-sqlite-storage/issues/399 and [Apache Cordova JIRA CB-10276](https://issues.apache.org/jira/browse/CB-10276) where there were intermittent problems with my sqlite plugin that were solved by wrapping its open database method like this:
> ```
> [self.commandDelegate runInBackground:^{
>     ...
> }];
> ```

In [Apache Cordova JIRA CB-10276](https://issues.apache.org/jira/browse/CB-10276) there is another comment about your cordova-plugin-printer project:
> Another 3rd party plugin that now causes 100% cpu is https://github.com/katzer/cordova-plugin-printer. This plugin must run in the main thread because calling UIKit from secondary thread causes errors and will be deprecated in future iOS releases.

ADDITIONAL NOTE: It _should_ be possible to solve the problem on the side of your plugin by simply running the operations in the background, as described above and also documented in the Threading section of https://cordova.apache.org/docs/en/latest/guide/platforms/ios/plugin.html (I have already done this in my sqlite plugin).

**Comment by katzer** [comment]
@brodybits, thanks for your hint. As the plugin uses UIKit it cannot run in background thread.

```
This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes. This will cause an exception in a future release.
```

**Comment by blckshrk** [comment]
Hi,

As the plugin can't run in background thread, is there a solution to do not freeze the UI during printing ? I have a GIF running during printing, but it freezed during content upload to the printing. I'm looking for a possible solution...

Thanks

**Comment by brianwalleshauser** [comment]
@katzer are there any plans for a resolution to this problem?
