### ISSUE TITLE
Setting bounds not working on all Printers

### ISSUE THREAD

**Issue by Jaspur** [katzer/cordova-plugin-printer#69]
When I do this:
```
$cordovaPrinter.print('https://foobar.com/'+item.id, { landscape: true, bounds: [0, 0, 0, 0] });
```
The bounds are still de default ones.

**Comment by katzer** [comment]
@Jaspur, `bounds` does not specify the final position of the popover. Thats always centered.

From the docs:
> A rectangle that defines the area from which the printing popover view is animated.
