### ISSUE TITLE
deprecated function reference

### ISSUE THREAD

**Issue by greggreenhaw** [katzer/cordova-plugin-printer#71]
I'm getting this message in IOS 4.0.1 cordova build.
Implicit declaration of function 'CDV_IsIPad' is invalid in C99

**Comment by RemnantArcher** [comment]
I can confirm this issue. I'm not able to build for ios at all due to this error.

**Comment by elfadotonto** [comment]
There too

**Comment by mfkuntz** [comment]
I have the same issue. Someone made a PR #74 which looks like it should clear this up.

**Comment by purid** [comment]
This worked for me too.
