### ISSUE TITLE
Is css supported?

### ISSUE THREAD

**Issue by JSkeeper** [katzer/cordova-plugin-printer#72]
I want to print my html content,but my css not work when I preview.

**Comment by purid** [comment]
Hi - any success with it? I have foundation working behind angular website. if I print from the website directly- the print is fine (same as large layout). But if I print from cordova app - it comes without css classes. 

Thanks

**Comment by AshwinKamathB** [comment]
Are you able to achieve.

**Comment by rk-panchal** [comment]
i fase same  issue metnion here

**Comment by citylims** [comment]
Print templates are limited to inline styles.

**Comment by rk-panchal** [comment]
Thanks @citylims 
According to  you  without inline css  karzer printer plugin  not well working

**Comment by katzer** [comment]
Please see the [example branch](https://github.com/katzer/cordova-plugin-printer/tree/example) which uses css classes. Works for Android and iOS.

**Comment by macsupport** [comment]
The example branch shows how to print a  sample content with this code, which includes the css but also the html to be printed:

     print: function () {
        var options = { name: 'awesome', printerId: app.printerId },
            page    = '';
     page += '<style type="text/css">html, body {width: 100%; height: 100%; margin: 0px; padding: 0px;}html {background: rgb(246, 248, 248);}body {font-family: "Open Sans", sans-serif;font-size: 14px;font-weight: 400;}.promos {position: absolute;left: 50%;top: 50%;transform: translate(-50%, -50%) scale(1.3);width: 800px;margin-left: 25px;}.promo {width: 250px;background: #0F1012;color: #f9f9f9;float: left;}.deal {padding: 10px 0 0 0;}.deal span {display: block;text-align: center;}.deal span:first-of-type {font-size: 23px;}.deal span:last-of-type {font-size: 13px;}.promo .price {display: block;width: 250px;background: #292b2e;margin: 15px 0 10px 0;text-align: center;font-size: 23px;padding: 17px 0 17px 0;}ul {display: block;margin: 20px 0 10px 0;padding: 0;list-style-type: none;text-align: center;color: #999999;}li {display: block;margin: 10px 0 0 0;}button {border: none;border-radius: 40px;background: #292b2e;color: #f9f9f9;padding: 10px 37px;margin: 10px 0 20px 60px;}.scale {transform: scale(1.2);box-shadow: 0 0 4px 1px rgba(20, 20, 20, 0.8);}.scale button {background: #64AAA4;}.scale .price {color: #64AAA4;}</style>';
        page += '<body><div class="promos"><div class="promo"><div class="deal"><span>Premium</span><span>This is really a good deal!</span></div><span class="price">$79</span><ul class="features"><li>Some great feature</li><li>Another super feature</li><li>And more...</li></ul><button>Sign up</button></div><div class="promo scale"><div class="deal"><span>Plus</span><span>This is really a good deal!</span></div><span class="price">$89</span><ul class="features"><li>Some great feature</li><li>Another super feature</li><li>And more...</li></ul><button>Sign up</button></div><div class="promo"><div class="deal"><span>Basic</span><span>Basic membership</span></div><span class="price">$69</span><ul class="features"><li>Choose the one on the left</li><li>We need moneyy</li><li>And more...</li></ul><button>Sign up</button></div></div></body>';

        cordova.plugins.printer.print(page, options, function (res) {
            alert(res ? 'Done' : 'Canceled');
        });
    }
Do you have an example how one might add the css but not the html using this example code:

    var page = document.getElementById('legal-notice');
    cordova.plugins.printer.print(page, 'Document.html');

**Comment by akhilesh1989** [comment]
CSS not supporting for iOS, css classes gets printed using <style type="text/css"></style>, while it's getting rendered on Android.

**Comment by kamzam777** [comment]
What works for me (Only tested in Android) is to send to print all the html content not only the body as follows:

`    var page= document.documentElement.innerHTML;
    cordova.plugins.printer.print(page, 'Document.html');`

**Comment by aewon** [comment]
This is what i did - altering the example that macsupport provided above 
my css is an external file. So i uploaded it using Fetch and saved it on a variable just as you would assign a json file to a variable.
```
loadFile(css-filename(css)=>{
page+='<style type='text/css'>"+css+ "<style>"
})
```
then i just attached the element that I needed to print to the page variable
`page+=myDIV.outerHTML`


i hope this helps.
