### ISSUE TITLE
How can i support android version >4.0 in a Cordova App with this plugin

### ISSUE THREAD

**Issue by MayankLogiciel** [katzer/cordova-plugin-printer#73]
I want to support print on android version >4.0 . So how can i install two different print plugin versions in my cordova app (master branch & google cloud print branch) simultaneously to support all devices.

**Comment by katzer** [comment]
@MayankLogiciel thats not possible as different plugin versions share the same namespaces. And since mostly any Android device is running KitKat or newer now the master branch does only support the Android Printing Framework.
