### ISSUE TITLE
Print Preview is not working in 0.7.1 version ??

### ISSUE THREAD

**Issue by manpreet-logiciel** [katzer/cordova-plugin-printer#75]
I am passing file uri for printing documents and images  but preview is not showing while printing the documents and images.Even i tried with remote web page but i am getting the same problem.Can u tell me why it is not previewing any document while printing.??

**Comment by katzer** [comment]
@manpreet-logiciel You have to provide HTML snippets and no file uri.

```javascript
cordova.plugins.print("<html>...</html>");
