### ISSUE TITLE
Fails for ios with error on Appprinter file.

### ISSUE THREAD

**Issue by purid** [katzer/cordova-plugin-printer#77]
Hi - It is failing when I build custom app for ios (Android is fine). Xcode is working fine for example. Any Hint:

Undefined symbols for architecture i386:
  "_CDV_IsIPad", referenced from:
      -[APPPrinter presentPrintController:fromRect:] in APPPrinter.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by filipe-nunes** [comment]
Head to platforms/ios/PROJECT_NAME/Plugins/APPPrinter.m and change the faulty line:

> if(CDV_IsIPad()) {

to:

> if([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad) {

**Comment by rockneverdies55** [comment]
Thank you @filipe-nunes that fixed the problem for me. Should that change be pulled in then maybe?

**Comment by katzer** [comment]
Has been fixed
