### ISSUE TITLE
Is there any way to print a document "silently" on Android without displaying the preview page?

### ISSUE THREAD

**Issue by multilexus** [katzer/cordova-plugin-printer#78]
Hi, I've been using this plugin and it works perfectly but I wonder if there's any way to print a document "silently" without displaying the preview? Every time I click print, it display options like SaveToPdf etc. I just want to print to a specific printer directly without any prompts. Any suggestions? Thanks,
Alex S.

**Comment by EionRobb** [comment]
PrintHand have an Android API that lets you print in the background, but you can't do the same through the Android print system

**Comment by ionSpark** [comment]
Hey muiltexus you ever figure this out? Gave a look at PrintHand and it looks promising.  He has examples here.. https://github.com/DynamixSoftware/PrintingSample .  Not a java guy but im gonna give it a try this weekend.

**Comment by EionRobb** [comment]
@ionSpark I have code for an older version of phonegap at https://github.com/EionRobb/phonegap-print-plugins/blob/master/Android/PrintHandPlugin.java if that helps save some time

**Comment by multilexus** [comment]
Hi guys! I haven't figured it out yet, but PrintHand does indeed look promising after reading their detailed info! Previously I did install PrintHand on my device, as well as PrinterShare Print Service, but I didn't spend enough time with it. Please let me know if you get it working. Regards, Alex $.

**Comment by multilexus** [comment]
Hi, ionSpark!
Did you have a chance to work on this issue? Any luck?

Thanks,Alex S.

**Comment by ionSpark** [comment]
@multilexus, Ya i did but i realized that it didn't support a printer i needed and that you would have to have the printhand app installed.  Its $10 dollars a device, as a enterprise app i could swing that but i've decided to wait and focus on other parts of the app at this moment.  When i get time ill post it on github.

**Comment by multilexus** [comment]
Printhand supports 3 methods of integration and method #3 (direct integration with their PrintingServices library) uses their proprietary Printing SDK and does NOT require PrintHand app to be installed on the device. I'm still struggling to make it work but not giving up yet :) I got their sample native PrintingSample app built into an APK and running on my Android tablet but its still using PrintHand app in addition to calling PrintingServices provided by their SDK. Getting in touch with their support team for help. I'll still have to make a cordova plugin out of it later. If you have that part working I'd really appreciate your help. 
On Mar 30, 2016 7:37 PM, ionSpark <notifications@github.com> wrote:@multilexus, Ya i did but i realized that it didn't support a printer i needed and that you would have to have the printhand app installed.  Its $10 dollars a device, as a enterprise app i could swing that but i've decided to wait and focus on other parts of the app at this moment.  When i get time ill post it on github.

**Comment by katzer** [comment]
@multilexus, as the others pointed out the Android printing framework does not provide such way.

**Comment by naveenmah** [comment]
I think Samsung Print Service Ca be used in this scenario.  It supports most of the vendors printers and it also have API using which you can print from background with out using Android Print Dialog.

**Comment by ostrichegret** [comment]
Is there a way to print silently without preview page to google cloud print / classic printer ( windows printer sharing ) / new printer with WiFi Direct?

Thank you

**Comment by saberprashant** [comment]
Hi @multilexus  @EionRobb @katzer @naveenmah @ostrichegret , 
Is there any way now (which wasn't there in past) in Android, to print silently (that is, without the pop-up page appearance) or any good cordova plugin which can provide the silent printing facility mainly for android.  
Thanks :)

**Comment by Phoenix-Alpha** [comment]
Hi @katzer.
Direct/silent printing is really essential for android platform and many users of this plugin seem to want this feature.
I hope you would find out the way to do this. Thanks.

**Comment by tmbax0098** [comment]
OMG , I need android silent print

**Comment by gmuth** [comment]
This might not be a solution for this plugin. However I'd like to point out that my kotlin/jvm library supports silent printing from Android (for documents in a format supported by the printer):
https://github.com/gmuth/ipp-client-kotlin

**Comment by jasonLiu001** [comment]
> This might not be a solution for this plugin. However I'd like to point out that my kotlin/jvm library supports silent printing from Android (for documents in a format supported by the printer): https://github.com/gmuth/ipp-client-kotlin

Thanks! That was very helpful.  Your library works for me! Now I can print from my Android app silently without any user interaction.
