### ISSUE TITLE
Please put on NPM

### ISSUE THREAD

**Issue by cepm-nate** [katzer/cordova-plugin-printer#82]
Searching [npmjs.com](https://www.npmjs.com/search?q=cordova+plugin+print) does not return your plugin.

**Comment by citylims** [comment]
https://www.npmjs.com/package/de.appplant.cordova.plugin.printer

**Comment by katzer** [comment]
Its coming soon as I am working on a new release. With that the new id will be `cordoba-plugin-printer`

**Comment by katzer** [comment]
https://www.npmjs.com/package/cordova-plugin-printer
