### ISSUE TITLE
Printer option

### ISSUE THREAD

**Issue by ansgmlen** [katzer/cordova-plugin-printer#88]
Hi @katzer  thank you for supporting cordova printer! it's awesome!
I integrated this and I have a question. Is there way skip printer options page for iOS airprint ?
I don't want to display printer options but it looks like it has to.
Thanks!

**Comment by ansgmlen** [comment]
Additionally  when I try to print, pages are always three. Even I add one letter. (tested on ipad2)

**Comment by katzer** [comment]
Hi @ansgmlen, by assigning values to all available options (by default) then these options won't be displayed. Additionally as I am going to release a new version I've added some iOS-specific properties to hide the control for page range of number of copies. See ea404a0acdac0d1f13c3c5f8e481a0b7d63c7e4f

**Comment by katzer** [comment]
> Additionally when I try to print, pages are always three.

Not in my case...
