### ISSUE TITLE
Print orientation

### ISSUE THREAD

**Issue by nicolinden** [katzer/cordova-plugin-printer#89]
Hi all, 

we use this plugin within an SAP Fiori Client app on the iPhone. We can successful print with it but the orientation is always in portrait and besides that it also contains a lot of whitespace margins to the right of the printable content (which makes the content on paper extremely small). Is there a way how we can control this?

Regards, 
Nico

![img_1250](https://cloud.githubusercontent.com/assets/13468895/16493383/8f1190a4-3ee5-11e6-8422-4ff75e1ec8be.PNG)

**Comment by katzer** [comment]
@nicolinden try to setting `orientation: null`. Then if the printer supports toggling between _landscape_ and _portrait_ there should be visible that option. Otherwise the printer may not support it.
