### ISSUE TITLE
To all forks that are ahead of the master branch

### ISSUE THREAD

**Issue by katzer** [katzer/cordova-plugin-printer#91]
Dear community,

I am going to work on a new update of the plugin now. So if you have a fork ahead of master please send a PR.

Thanks!

**Comment by OscarGelvez** [comment]
I 'm trying to print to my device, but I try to keep mistake, and I restart the application . help me.
Error : Error loading active assets / natives_blob_64.bin : java.io.FileNotFoundException : Active / natives_blob_64.bin
validate_display : 255 Error 3008 ( EGL_BAD_DISPLAY )
