### ISSUE TITLE
Error saving the pdf file on my device

### ISSUE THREAD

**Issue by OscarGelvez** [katzer/cordova-plugin-printer#92]
error saving the pdf file on my device

I try to save the pdf file generated by the plugin but when I choose a (internal or sd) folder and press the save button, the screen of my device is placed black and restart the app to your main view.

to follow the android logcat gives me these errors:

code from my controller:
```javascript
var page = document.getElementById('prueba');



document.addEventListener('deviceready', function () {
    // cordova.plugins.printer is now available
   $scope.print = function() {
        if($cordovaPrinter.isAvailable()) {
           cordova.plugins.printer.print(page, 'Document.html', function () {
    alert('printing finished or canceled')
});
        } else {
            alert("Printing is not available on device");
        }
    }

}, false);
 ```

I'm working on ionic, angular...
![errores](https://cloud.githubusercontent.com/assets/15203114/17086371/c832a2be-51b5-11e6-9bf5-39630780189b.PNG)

Thank you can help me katzer

**Comment by katzer** [comment]
@OscarGelvez, that looks strange.

Can you try out the following:

1. Rename `Document.html` to `Document`
2. Replace page through by a sample string like `<h1>Test</h1>`

**Comment by OscarGelvez** [comment]
Katzer've tried what you recommended to me and it works. but I need it is to keep part of an HTML document, and test like this: var page = document.getElementById ('flag'); it worked 2 times but has failed again. and he returned the same error as you send in the picture attached last time.


I work with angular.js, html document and have it loaded by the controller where run the plugin.

You saw strange in the code that send to you? thanks for your prompt response, I hope to help me soon.

**Comment by katzer** [comment]
Hi @OscarGelvez, you can try to resolve the `FileNotFoundException`by changing the path. The base url points to `assets/www/`.

So `assets/native_blob_64.bin` should be `../native_blob_64.bin`.
