### ISSUE TITLE
Print without printer selection on android

### ISSUE THREAD

**Issue by iffifan** [katzer/cordova-plugin-printer#93]
Hello

I saw that on ios we can print without using printer selection. 
Is this possible on android? I know currently it is not supported but can it be added for android?

Thank you for your support

**Comment by katzer** [comment]
@iffifan At the moment it's not possible and Android has to public API for that. But I hope to add it anyway.

**Comment by katzer** [comment]
@iffifan Sadly it's not possible without having having root access.

**Comment by iffifan** [comment]
I am willing to hire a developer who can help us do this even if root access of device is required. 
Anybody interested?
