### ISSUE TITLE
error saving the file in pdf

### ISSUE THREAD

**Issue by OscarGelvez** [katzer/cordova-plugin-printer#95]
Hello Friend
I am using your plugin but I have the following errors.

I have not used the plugin to print to a printer, only to save the PDF file or upload it to google drive. In both cases logcat shows me the following errors:

You could tell me how I can use your plugin only to save the file in PDF ... as I can disable the printing process and leave only save on the device?

I appreciate your response
![captura de pantalla 50](https://cloud.githubusercontent.com/assets/15203114/18023224/2005106a-6bbc-11e6-94b5-9e0d9c7c3e1a.png)

**Comment by katzer** [comment]
@OscarGelvez Does the trace log indicate any code from plugin? Class and line?

**Comment by OscarGelvez** [comment]
Friend the problem was of my device and the Android version 5.0.2.

use the plugin on other devices with android 5.1 and 4.4.2 and it worked correctly. I bring you this information, thank you for your answer.

**Comment by aviral1** [comment]
yes it can work only 4.4.4 and above versions of android..
