### ISSUE TITLE
pull-right class not working

### ISSUE THREAD

**Issue by sunojvijayan** [katzer/cordova-plugin-printer#99]
Hi I have an html div with elements in it. Some of them have 'class="pull-right"'. But when i print its not working. Those divs are brought down to the next line. Please help

**Comment by sunojvijayan** [comment]
Hi any update on this. please

**Comment by katzer** [comment]
Guess `pull-right` comes from your CSS rules. Make sure that they got loaded together with your HTML. The example branch contains an sample with HTML and CSS.
